using AgentsDataView.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AgentsDataView.Server.Entities.ModelConfigurations
{
    public class CityConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder.ToTable("Cities","dbo");
            builder.HasKey(c => c.Id);
            builder.Property(c => c.Id).ValueGeneratedOnAdd();

            builder.HasOne(c => c.Province)
                .WithMany(p => p.Cities)
                .HasForeignKey(c => c.ProvinceId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            builder.HasData(
                new() { Id = 1, Code = 1, CityName = "اردبيل", ProvinceId = 3 },
                new() { Id = 2, Code = 2, CityName = "اصلاندوز", ProvinceId = 3 },
                new() { Id = 3, Code = 3, CityName = "آبي بيگلو", ProvinceId = 3 },
                new() { Id = 4, Code = 4, CityName = "بيله سوار", ProvinceId = 3 },
                new() { Id = 5, Code = 5, CityName = "پارس آباد", ProvinceId = 3 },
                new() { Id = 6, Code = 6, CityName = "تازه كند", ProvinceId = 3 },
                new() { Id = 7, Code = 7, CityName = "تازه كندانگوت", ProvinceId = 3 },
                new() { Id = 8, Code = 8, CityName = "جعفرآباد", ProvinceId = 3 },
                new() { Id = 9, Code = 9, CityName = "خلخال", ProvinceId = 3 },
                new() { Id = 10, Code = 10, CityName = "رضي", ProvinceId = 3 },
                new() { Id = 11, Code = 11, CityName = "سرعين", ProvinceId = 3 },
                new() { Id = 12, Code = 12, CityName = "عنبران", ProvinceId = 3 },
                new() { Id = 13, Code = 13, CityName = "فخرآباد", ProvinceId = 3 },
                new() { Id = 14, Code = 14, CityName = "كلور", ProvinceId = 3 },
                new() { Id = 15, Code = 15, CityName = "كوراييم", ProvinceId = 3 },
                new() { Id = 16, Code = 16, CityName = "گرمي", ProvinceId = 3 },
                new() { Id = 17, Code = 17, CityName = "گيوي", ProvinceId = 3 },
                new() { Id = 18, Code = 18, CityName = "لاهرود", ProvinceId = 3 },
                new() { Id = 19, Code = 19, CityName = "مرادلو", ProvinceId = 3 },
                new() { Id = 20, Code = 20, CityName = "مشگين شهر", ProvinceId = 3 },
                new() { Id = 21, Code = 21, CityName = "نمين", ProvinceId = 3 },
                new() { Id = 22, Code = 22, CityName = "نير", ProvinceId = 3 },
                new() { Id = 23, Code = 23, CityName = "هشتجين", ProvinceId = 3 },
                new() { Id = 24, Code = 24, CityName = "هير", ProvinceId = 3 },
                new() { Id = 25, Code = 25, CityName = "ابريشم", ProvinceId = 4 },
                new() { Id = 26, Code = 26, CityName = "ابوزيدآباد", ProvinceId = 4 },
                new() { Id = 27, Code = 27, CityName = "اردستان", ProvinceId = 4 },
                new() { Id = 28, Code = 28, CityName = "اژيه", ProvinceId = 4 },
                new() { Id = 29, Code = 29, CityName = "اصفهان", ProvinceId = 4 },
                new() { Id = 30, Code = 30, CityName = "افوس", ProvinceId = 4 },
                new() { Id = 31, Code = 31, CityName = "انارك", ProvinceId = 4 },
                new() { Id = 32, Code = 32, CityName = "ايمانشهر", ProvinceId = 4 },
                new() { Id = 33, Code = 33, CityName = "آران وبيدگل", ProvinceId = 4 },
                new() { Id = 34, Code = 34, CityName = "بادرود", ProvinceId = 4 },
                new() { Id = 35, Code = 35, CityName = "باغ بهادران", ProvinceId = 4 },
                new() { Id = 36, Code = 36, CityName = "بافران", ProvinceId = 4 },
                new() { Id = 37, Code = 37, CityName = "برزك", ProvinceId = 4 },
                new() { Id = 38, Code = 38, CityName = "برف انبار", ProvinceId = 4 },
                new() { Id = 39, Code = 39, CityName = "بوئين ومياندشت", ProvinceId = 4 },
                new() { Id = 40, Code = 40, CityName = "بهاران شهر", ProvinceId = 4 },
                new() { Id = 41, Code = 41, CityName = "بهارستان", ProvinceId = 4 },
                new() { Id = 42, Code = 42, CityName = "پيربكران", ProvinceId = 4 },
                new() { Id = 43, Code = 43, CityName = "تودشك", ProvinceId = 4 },
                new() { Id = 44, Code = 44, CityName = "تيران", ProvinceId = 4 },
                new() { Id = 45, Code = 45, CityName = "جندق", ProvinceId = 4 },
                new() { Id = 46, Code = 46, CityName = "جوزدان", ProvinceId = 4 },
                new() { Id = 47, Code = 47, CityName = "جوشقان وكامو", ProvinceId = 4 },
                new() { Id = 48, Code = 48, CityName = "چادگان", ProvinceId = 4 },
                new() { Id = 49, Code = 49, CityName = "چرمهين", ProvinceId = 4 },
                new() { Id = 50, Code = 50, CityName = "چمگردان", ProvinceId = 4 },
                new() { Id = 51, Code = 51, CityName = "حبيب آباد", ProvinceId = 4 },
                new() { Id = 52, Code = 52, CityName = "حسن آباد", ProvinceId = 4 },
                new() { Id = 53, Code = 53, CityName = "حنا", ProvinceId = 4 },
                new() { Id = 54, Code = 54, CityName = "خالدآباد", ProvinceId = 4 },
                new() { Id = 55, Code = 55, CityName = "خميني شهر", ProvinceId = 4 },
                new() { Id = 56, Code = 56, CityName = "خوانسار", ProvinceId = 4 },
                new() { Id = 57, Code = 57, CityName = "خور", ProvinceId = 4 },
                new() { Id = 58, Code = 58, CityName = "خوراسگان", ProvinceId = 4 },
                new() { Id = 59, Code = 59, CityName = "خورزوق", ProvinceId = 4 },
                new() { Id = 60, Code = 60, CityName = "داران", ProvinceId = 4 },
                new() { Id = 61, Code = 61, CityName = "دامنه", ProvinceId = 4 },
                new() { Id = 62, Code = 62, CityName = "درچه پياز", ProvinceId = 4 },
                new() { Id = 63, Code = 63, CityName = "دستگرد", ProvinceId = 4 },
                new() { Id = 64, Code = 64, CityName = "دولت آباد", ProvinceId = 4 },
                new() { Id = 65, Code = 65, CityName = "دهاقان", ProvinceId = 4 },
                new() { Id = 66, Code = 66, CityName = "دهق", ProvinceId = 4 },
                new() { Id = 67, Code = 67, CityName = "ديزيچه", ProvinceId = 4 },
                new() { Id = 68, Code = 68, CityName = "رزوه", ProvinceId = 4 },
                new() { Id = 69, Code = 69, CityName = "رضوانشهر", ProvinceId = 4 },
                new() { Id = 70, Code = 70, CityName = "زاينده رود", ProvinceId = 4 },
                new() { Id = 71, Code = 71, CityName = "زرين شهر", ProvinceId = 4 },
                new() { Id = 72, Code = 72, CityName = "زواره", ProvinceId = 4 },
                new() { Id = 73, Code = 73, CityName = "زيباشهر", ProvinceId = 4 },
                new() { Id = 74, Code = 74, CityName = "سده لنجان", ProvinceId = 4 },
                new() { Id = 75, Code = 75, CityName = "سفيدشهر", ProvinceId = 4 },
                new() { Id = 76, Code = 76, CityName = "سگزي", ProvinceId = 4 },
                new() { Id = 77, Code = 77, CityName = "سميرم", ProvinceId = 4 },
                new() { Id = 78, Code = 78, CityName = "شاپورآباد", ProvinceId = 4 },
                new() { Id = 79, Code = 79, CityName = "شاهين شهر", ProvinceId = 4 },
                new() { Id = 80, Code = 80, CityName = "شهرضا", ProvinceId = 4 },
                new() { Id = 81, Code = 81, CityName = "طالخونچه", ProvinceId = 4 },
                new() { Id = 82, Code = 82, CityName = "عسگران", ProvinceId = 4 },
                new() { Id = 83, Code = 83, CityName = "علويچه", ProvinceId = 4 },
                new() { Id = 84, Code = 84, CityName = "فرخي", ProvinceId = 4 },
                new() { Id = 85, Code = 85, CityName = "فريدونشهر", ProvinceId = 4 },
                new() { Id = 86, Code = 86, CityName = "فلاورجان", ProvinceId = 4 },
                new() { Id = 87, Code = 87, CityName = "فولادشهر", ProvinceId = 4 },
                new() { Id = 88, Code = 88, CityName = "قمصر", ProvinceId = 4 },
                new() { Id = 89, Code = 89, CityName = "قهجاورستان", ProvinceId = 4 },
                new() { Id = 90, Code = 90, CityName = "قهدريجان", ProvinceId = 4 },
                new() { Id = 91, Code = 91, CityName = "كاشان", ProvinceId = 4 },
                new() { Id = 92, Code = 92, CityName = "كركوند", ProvinceId = 4 },
                new() { Id = 93, Code = 93, CityName = "كليشادوسودرجان", ProvinceId = 4 },
                new() { Id = 94, Code = 94, CityName = "كمشچه", ProvinceId = 4 },
                new() { Id = 95, Code = 95, CityName = "كمه", ProvinceId = 4 },
                new() { Id = 96, Code = 96, CityName = "كوشك", ProvinceId = 4 },
                new() { Id = 97, Code = 97, CityName = "كوهپايه", ProvinceId = 4 },
                new() { Id = 98, Code = 98, CityName = "كهريزسنگ", ProvinceId = 4 },
                new() { Id = 99, Code = 99, CityName = "گرگاب", ProvinceId = 4 },
                new() { Id = 100, Code = 100, CityName = "گزبرخوار", ProvinceId = 4 },
                new() { Id = 101, Code = 101, CityName = "گلپايگان", ProvinceId = 4 },
                new() { Id = 102, Code = 102, CityName = "گلدشت", ProvinceId = 4 },
                new() { Id = 103, Code = 103, CityName = "گلشن", ProvinceId = 4 },
                new() { Id = 104, Code = 104, CityName = "گلشهر", ProvinceId = 4 },
                new() { Id = 105, Code = 105, CityName = "گوگد", ProvinceId = 4 },
                new() { Id = 106, Code = 106, CityName = "لاي بيد", ProvinceId = 4 },
                new() { Id = 107, Code = 107, CityName = "مباركه", ProvinceId = 4 },
                new() { Id = 108, Code = 108, CityName = "محمدآباد", ProvinceId = 4 },
                new() { Id = 109, Code = 109, CityName = "مشكات", ProvinceId = 4 },
                new() { Id = 110, Code = 110, CityName = "منظريه", ProvinceId = 4 },
                new() { Id = 111, Code = 111, CityName = "مهاباد", ProvinceId = 4 },
                new() { Id = 112, Code = 112, CityName = "ميمه", ProvinceId = 4 },
                new() { Id = 113, Code = 113, CityName = "نائين", ProvinceId = 4 },
                new() { Id = 114, Code = 114, CityName = "نجف آباد", ProvinceId = 4 },
                new() { Id = 115, Code = 115, CityName = "نصرآباد", ProvinceId = 4 },
                new() { Id = 116, Code = 116, CityName = "نطنز", ProvinceId = 4 },
                new() { Id = 117, Code = 117, CityName = "نوش آباد", ProvinceId = 4 },
                new() { Id = 118, Code = 118, CityName = "نياسر", ProvinceId = 4 },
                new() { Id = 119, Code = 119, CityName = "نيك آباد", ProvinceId = 4 },
                new() { Id = 120, Code = 120, CityName = "ورزنه", ProvinceId = 4 },
                new() { Id = 121, Code = 121, CityName = "ورنامخواست", ProvinceId = 4 },
                new() { Id = 122, Code = 122, CityName = "وزوان", ProvinceId = 4 },
                new() { Id = 123, Code = 123, CityName = "ونك", ProvinceId = 4 },
                new() { Id = 124, Code = 124, CityName = "هرند", ProvinceId = 4 },
                new() { Id = 125, Code = 125, CityName = "اشتهارد", ProvinceId = 31 },
                new() { Id = 126, Code = 126, CityName = "آسارا", ProvinceId = 31 },
                new() { Id = 127, Code = 127, CityName = "تنكمان", ProvinceId = 31 },
                new() { Id = 128, Code = 128, CityName = "چهارباغ", ProvinceId = 31 },
                new() { Id = 129, Code = 129, CityName = "سيف آباد", ProvinceId = 31 },
                new() { Id = 130, Code = 130, CityName = "شهرجديدهشتگرد", ProvinceId = 31 },
                new() { Id = 131, Code = 131, CityName = "طالقان", ProvinceId = 31 },
                new() { Id = 132, Code = 132, CityName = "كرج", ProvinceId = 31 },
                new() { Id = 133, Code = 133, CityName = "كمال شهر", ProvinceId = 31 },
                new() { Id = 134, Code = 134, CityName = "كوهسار", ProvinceId = 31 },
                new() { Id = 135, Code = 135, CityName = "گرمدره", ProvinceId = 31 },
                new() { Id = 136, Code = 136, CityName = "ماهدشت", ProvinceId = 31 },
                new() { Id = 137, Code = 137, CityName = "محمدشهر", ProvinceId = 31 },
                new() { Id = 138, Code = 138, CityName = "مشكين دشت", ProvinceId = 31 },
                new() { Id = 139, Code = 139, CityName = "نظرآباد", ProvinceId = 31 },
                new() { Id = 140, Code = 140, CityName = "هشتگرد", ProvinceId = 31 },
                new() { Id = 141, Code = 141, CityName = "اركواز", ProvinceId = 5 },
                new() { Id = 142, Code = 142, CityName = "ايلام", ProvinceId = 5 },
                new() { Id = 143, Code = 143, CityName = "ايوان", ProvinceId = 5 },
                new() { Id = 144, Code = 144, CityName = "آبدانان", ProvinceId = 5 },
                new() { Id = 145, Code = 145, CityName = "آسمان آباد", ProvinceId = 5 },
                new() { Id = 146, Code = 146, CityName = "بدره", ProvinceId = 5 },
                new() { Id = 147, Code = 147, CityName = "پهله", ProvinceId = 5 },
                new() { Id = 148, Code = 148, CityName = "توحيد", ProvinceId = 5 },
                new() { Id = 149, Code = 149, CityName = "چوار", ProvinceId = 5 },
                new() { Id = 150, Code = 150, CityName = "دره شهر", ProvinceId = 5 },
                new() { Id = 151, Code = 151, CityName = "دلگشا", ProvinceId = 5 },
                new() { Id = 152, Code = 152, CityName = "دهلران", ProvinceId = 5 },
                new() { Id = 153, Code = 153, CityName = "زرنه", ProvinceId = 5 },
                new() { Id = 154, Code = 154, CityName = "سراب باغ", ProvinceId = 5 },
                new() { Id = 155, Code = 155, CityName = "سرابله", ProvinceId = 5 },
                new() { Id = 156, Code = 156, CityName = "صالح آباد", ProvinceId = 5 },
                new() { Id = 157, Code = 157, CityName = "لومار", ProvinceId = 5 },
                new() { Id = 158, Code = 158, CityName = "مورموري", ProvinceId = 5 },
                new() { Id = 159, Code = 159, CityName = "موسيان", ProvinceId = 5 },
                new() { Id = 160, Code = 160, CityName = "مهران", ProvinceId = 5 },
                new() { Id = 161, Code = 161, CityName = "ميمه ", ProvinceId = 5 },
                new() { Id = 162, Code = 162, CityName = "اسكو", ProvinceId = 1 },
                new() { Id = 163, Code = 163, CityName = "اهر", ProvinceId = 1 },
                new() { Id = 164, Code = 164, CityName = "ايلخچي", ProvinceId = 1 },
                new() { Id = 165, Code = 165, CityName = "آبش احمد", ProvinceId = 1 },
                new() { Id = 166, Code = 166, CityName = "آذرشهر", ProvinceId = 1 },
                new() { Id = 167, Code = 167, CityName = "آقكند", ProvinceId = 1 },
                new() { Id = 168, Code = 168, CityName = "باسمنج", ProvinceId = 1 },
                new() { Id = 169, Code = 169, CityName = "بخشايش", ProvinceId = 1 },
                new() { Id = 170, Code = 170, CityName = "بستان آباد", ProvinceId = 1 },
                new() { Id = 171, Code = 171, CityName = "بناب", ProvinceId = 1 },
                new() { Id = 172, Code = 172, CityName = "بناب جديد", ProvinceId = 1 },
                new() { Id = 173, Code = 173, CityName = "تبريز", ProvinceId = 1 },
                new() { Id = 174, Code = 174, CityName = "ترك", ProvinceId = 1 },
                new() { Id = 175, Code = 175, CityName = "تركمانچاي", ProvinceId = 1 },
                new() { Id = 176, Code = 176, CityName = "تسوج", ProvinceId = 1 },
                new() { Id = 177, Code = 177, CityName = "تيكمه داش", ProvinceId = 1 },
                new() { Id = 178, Code = 178, CityName = "جلفا", ProvinceId = 1 },
                new() { Id = 179, Code = 179, CityName = "خاروانا", ProvinceId = 1 },
                new() { Id = 180, Code = 180, CityName = "خامنه", ProvinceId = 1 },
                new() { Id = 181, Code = 181, CityName = "خراجو", ProvinceId = 1 },
                new() { Id = 182, Code = 182, CityName = "خسروشهر", ProvinceId = 1 },
                new() { Id = 183, Code = 183, CityName = "خمارلو", ProvinceId = 1 },
                new() { Id = 184, Code = 184, CityName = "خواجه", ProvinceId = 1 },
                new() { Id = 185, Code = 185, CityName = "دوزدوزان", ProvinceId = 1 },
                new() { Id = 186, Code = 186, CityName = "زرنق", ProvinceId = 1 },
                new() { Id = 187, Code = 187, CityName = "زنوز", ProvinceId = 1 },
                new() { Id = 188, Code = 188, CityName = "سراب", ProvinceId = 1 },
                new() { Id = 189, Code = 189, CityName = "سردرود", ProvinceId = 1 },
                new() { Id = 190, Code = 190, CityName = "سيس", ProvinceId = 1 },
                new() { Id = 191, Code = 191, CityName = "سيه رود", ProvinceId = 1 },
                new() { Id = 192, Code = 192, CityName = "شبستر", ProvinceId = 1 },
                new() { Id = 193, Code = 193, CityName = "شربيان", ProvinceId = 1 },
                new() { Id = 194, Code = 194, CityName = "شرفخانه", ProvinceId = 1 },
                new() { Id = 195, Code = 195, CityName = "شندآباد", ProvinceId = 1 },
                new() { Id = 196, Code = 196, CityName = "شهرجديدسهند", ProvinceId = 1 },
                new() { Id = 197, Code = 197, CityName = "صوفيان", ProvinceId = 1 },
                new() { Id = 198, Code = 198, CityName = "عجب شير", ProvinceId = 1 },
                new() { Id = 199, Code = 199, CityName = "قره آغاج", ProvinceId = 1 },
                new() { Id = 200, Code = 200, CityName = "كشكسراي", ProvinceId = 1 },
                new() { Id = 201, Code = 201, CityName = "كلوانق", ProvinceId = 1 },
                new() { Id = 202, Code = 202, CityName = "كليبر", ProvinceId = 1 },
                new() { Id = 203, Code = 203, CityName = "كوزه كنان", ProvinceId = 1 },
                new() { Id = 204, Code = 204, CityName = "گوگان", ProvinceId = 1 },
                new() { Id = 205, Code = 205, CityName = "ليلان", ProvinceId = 1 },
                new() { Id = 206, Code = 206, CityName = "مراغه", ProvinceId = 1 },
                new() { Id = 207, Code = 207, CityName = "مرند", ProvinceId = 1 },
                new() { Id = 208, Code = 208, CityName = "ملكان", ProvinceId = 1 },
                new() { Id = 209, Code = 209, CityName = "ممقان", ProvinceId = 1 },
                new() { Id = 210, Code = 210, CityName = "مهربان", ProvinceId = 1 },
                new() { Id = 211, Code = 211, CityName = "ميانه", ProvinceId = 1 },
                new() { Id = 212, Code = 212, CityName = "نظركهريزي", ProvinceId = 1 },
                new() { Id = 213, Code = 213, CityName = "وايقان", ProvinceId = 1 },
                new() { Id = 214, Code = 214, CityName = "ورزقان", ProvinceId = 1 },
                new() { Id = 215, Code = 215, CityName = "هاديشهر", ProvinceId = 1 },
                new() { Id = 216, Code = 216, CityName = "هريس", ProvinceId = 1 },
                new() { Id = 217, Code = 217, CityName = "هشترود", ProvinceId = 1 },
                new() { Id = 218, Code = 218, CityName = "هوراند", ProvinceId = 1 },
                new() { Id = 219, Code = 219, CityName = "يامچي", ProvinceId = 1 },
                new() { Id = 220, Code = 220, CityName = "ارومیه", ProvinceId = 2 },
                new() { Id = 221, Code = 221, CityName = "اشنويه", ProvinceId = 2 },
                new() { Id = 222, Code = 222, CityName = "ايواوغلي", ProvinceId = 2 },
                new() { Id = 223, Code = 223, CityName = "آواجيق", ProvinceId = 2 },
                new() { Id = 224, Code = 224, CityName = "باروق", ProvinceId = 2 },
                new() { Id = 225, Code = 225, CityName = "بازرگان", ProvinceId = 2 },
                new() { Id = 226, Code = 226, CityName = "بوكان", ProvinceId = 2 },
                new() { Id = 227, Code = 227, CityName = "پلدشت", ProvinceId = 2 },
                new() { Id = 228, Code = 228, CityName = "پيرانشهر", ProvinceId = 2 },
                new() { Id = 229, Code = 229, CityName = "تازه شهر", ProvinceId = 2 },
                new() { Id = 230, Code = 230, CityName = "تكاب", ProvinceId = 2 },
                new() { Id = 231, Code = 231, CityName = "چهاربرج", ProvinceId = 2 },
                new() { Id = 232, Code = 232, CityName = "خليفان", ProvinceId = 2 },
                new() { Id = 233, Code = 233, CityName = "خوي", ProvinceId = 2 },
                new() { Id = 234, Code = 234, CityName = "ديزج ديز", ProvinceId = 2 },
                new() { Id = 235, Code = 235, CityName = "ربط", ProvinceId = 2 },
                new() { Id = 236, Code = 236, CityName = "سردشت", ProvinceId = 2 },
                new() { Id = 237, Code = 237, CityName = "سرو", ProvinceId = 2 },
                new() { Id = 238, Code = 238, CityName = "سلماس", ProvinceId = 2 },
                new() { Id = 239, Code = 239, CityName = "سيلوانه", ProvinceId = 2 },
                new() { Id = 240, Code = 240, CityName = "سيمينه", ProvinceId = 2 },
                new() { Id = 241, Code = 241, CityName = "سيه چشمه", ProvinceId = 2 },
                new() { Id = 242, Code = 242, CityName = "شاهين دژ", ProvinceId = 2 },
                new() { Id = 243, Code = 243, CityName = "شوط", ProvinceId = 2 },
                new() { Id = 244, Code = 244, CityName = "فيرورق", ProvinceId = 2 },
                new() { Id = 245, Code = 245, CityName = "قره ضياءالدين", ProvinceId = 2 },
                new() { Id = 246, Code = 246, CityName = "قطور", ProvinceId = 2 },
                new() { Id = 247, Code = 247, CityName = "قوشچي", ProvinceId = 2 },
                new() { Id = 248, Code = 248, CityName = "كشاورز", ProvinceId = 2 },
                new() { Id = 249, Code = 249, CityName = "گردكشانه", ProvinceId = 2 },
                new() { Id = 250, Code = 250, CityName = "ماكو", ProvinceId = 2 },
                new() { Id = 251, Code = 251, CityName = "محمديار", ProvinceId = 2 },
                new() { Id = 252, Code = 252, CityName = "محمودآباد", ProvinceId = 2 },
                new() { Id = 253, Code = 253, CityName = "مهاباد ", ProvinceId = 2 },
                new() { Id = 254, Code = 254, CityName = "مياندوآب", ProvinceId = 2 },
                new() { Id = 255, Code = 255, CityName = "ميرآباد", ProvinceId = 2 },
                new() { Id = 256, Code = 256, CityName = "نالوس", ProvinceId = 2 },
                new() { Id = 257, Code = 257, CityName = "نقده", ProvinceId = 2 },
                new() { Id = 258, Code = 258, CityName = "نوشين", ProvinceId = 2 },
                new() { Id = 259, Code = 259, CityName = "امام حسن", ProvinceId = 6 },
                new() { Id = 260, Code = 260, CityName = "انارستان", ProvinceId = 6 },
                new() { Id = 261, Code = 261, CityName = "اهرم", ProvinceId = 6 },
                new() { Id = 262, Code = 262, CityName = "آبپخش", ProvinceId = 6 },
                new() { Id = 263, Code = 263, CityName = "آبدان", ProvinceId = 6 },
                new() { Id = 264, Code = 264, CityName = "برازجان", ProvinceId = 6 },
                new() { Id = 265, Code = 265, CityName = "بردخون", ProvinceId = 6 },
                new() { Id = 266, Code = 266, CityName = "بردستان", ProvinceId = 6 },
                new() { Id = 267, Code = 267, CityName = "بندردير", ProvinceId = 6 },
                new() { Id = 268, Code = 268, CityName = "بندرديلم", ProvinceId = 6 },
                new() { Id = 269, Code = 269, CityName = "بندرريگ", ProvinceId = 6 },
                new() { Id = 270, Code = 270, CityName = "بندركنگان", ProvinceId = 6 },
                new() { Id = 271, Code = 271, CityName = "بندرگناوه", ProvinceId = 6 },
                new() { Id = 272, Code = 272, CityName = "بنك", ProvinceId = 6 },
                new() { Id = 273, Code = 273, CityName = "بوشهر", ProvinceId = 6 },
                new() { Id = 274, Code = 274, CityName = "تنگ ارم", ProvinceId = 6 },
                new() { Id = 275, Code = 275, CityName = "جم", ProvinceId = 6 },
                new() { Id = 276, Code = 276, CityName = "چغادك", ProvinceId = 6 },
                new() { Id = 277, Code = 277, CityName = "خارك", ProvinceId = 6 },
                new() { Id = 278, Code = 278, CityName = "خورموج", ProvinceId = 6 },
                new() { Id = 279, Code = 279, CityName = "دالكي", ProvinceId = 6 },
                new() { Id = 280, Code = 280, CityName = "دلوار", ProvinceId = 6 },
                new() { Id = 281, Code = 281, CityName = "ريز", ProvinceId = 6 },
                new() { Id = 282, Code = 282, CityName = "سعدآباد", ProvinceId = 6 },
                new() { Id = 283, Code = 283, CityName = "سيراف", ProvinceId = 6 },
                new() { Id = 284, Code = 284, CityName = "شبانكاره", ProvinceId = 6 },
                new() { Id = 285, Code = 285, CityName = "شنبه", ProvinceId = 6 },
                new() { Id = 286, Code = 286, CityName = "عسلويه", ProvinceId = 6 },
                new() { Id = 287, Code = 287, CityName = "كاكي", ProvinceId = 6 },
                new() { Id = 288, Code = 288, CityName = "كلمه", ProvinceId = 6 },
                new() { Id = 289, Code = 289, CityName = "نخل تقي", ProvinceId = 6 },
                new() { Id = 290, Code = 290, CityName = "وحدتيه", ProvinceId = 6 },
                new() { Id = 291, Code = 291, CityName = "ارجمند", ProvinceId = 7 },
                new() { Id = 292, Code = 292, CityName = "اسلامشهر", ProvinceId = 7 },
                new() { Id = 293, Code = 293, CityName = "انديشه", ProvinceId = 7 },
                new() { Id = 294, Code = 294, CityName = "آبسرد", ProvinceId = 7 },
                new() { Id = 295, Code = 295, CityName = "آبعلي", ProvinceId = 7 },
                new() { Id = 296, Code = 296, CityName = "باغستان", ProvinceId = 7 },
                new() { Id = 297, Code = 297, CityName = "باقرشهر", ProvinceId = 7 },
                new() { Id = 298, Code = 298, CityName = "بومهن", ProvinceId = 7 },
                new() { Id = 299, Code = 299, CityName = "پاكدشت", ProvinceId = 7 },
                new() { Id = 300, Code = 300, CityName = "پرديس", ProvinceId = 7 },
                new() { Id = 301, Code = 301, CityName = "پيشوا", ProvinceId = 7 },
                new() { Id = 302, Code = 302, CityName = "تجريش", ProvinceId = 7 },
                new() { Id = 303, Code = 303, CityName = "تهران", ProvinceId = 7 },
                new() { Id = 304, Code = 304, CityName = "جوادآباد", ProvinceId = 7 },
                new() { Id = 305, Code = 305, CityName = "چهاردانگه", ProvinceId = 7 },
                new() { Id = 306, Code = 306, CityName = "حسن آباد ", ProvinceId = 7 },
                new() { Id = 307, Code = 307, CityName = "دماوند", ProvinceId = 7 },
                new() { Id = 308, Code = 308, CityName = "رباط كريم", ProvinceId = 7 },
                new() { Id = 309, Code = 309, CityName = "رودهن", ProvinceId = 7 },
                new() { Id = 310, Code = 310, CityName = "ري", ProvinceId = 7 },
                new() { Id = 311, Code = 311, CityName = "شاهدشهر", ProvinceId = 7 },
                new() { Id = 312, Code = 312, CityName = "شريف آباد", ProvinceId = 7 },
                new() { Id = 313, Code = 313, CityName = "شهريار", ProvinceId = 7 },
                new() { Id = 314, Code = 314, CityName = "صالح آباد ", ProvinceId = 7 },
                new() { Id = 315, Code = 315, CityName = "صباشهر", ProvinceId = 7 },
                new() { Id = 316, Code = 316, CityName = "صفادشت", ProvinceId = 7 },
                new() { Id = 317, Code = 317, CityName = "فردوسيه", ProvinceId = 7 },
                new() { Id = 318, Code = 318, CityName = "فرون آباد", ProvinceId = 7 },
                new() { Id = 319, Code = 319, CityName = "فشم", ProvinceId = 7 },
                new() { Id = 320, Code = 320, CityName = "فيروزكوه", ProvinceId = 7 },
                new() { Id = 321, Code = 321, CityName = "قدس", ProvinceId = 7 },
                new() { Id = 322, Code = 322, CityName = "قرچك", ProvinceId = 7 },
                new() { Id = 323, Code = 323, CityName = "كهريزك", ProvinceId = 7 },
                new() { Id = 324, Code = 324, CityName = "كيلان", ProvinceId = 7 },
                new() { Id = 325, Code = 325, CityName = "گلستان", ProvinceId = 7 },
                new() { Id = 326, Code = 326, CityName = "لواسان", ProvinceId = 7 },
                new() { Id = 327, Code = 327, CityName = "ملارد", ProvinceId = 7 },
                new() { Id = 328, Code = 328, CityName = "نسيم شهر", ProvinceId = 7 },
                new() { Id = 329, Code = 329, CityName = "نصيرآباد", ProvinceId = 7 },
                new() { Id = 330, Code = 330, CityName = "وحيديه", ProvinceId = 7 },
                new() { Id = 331, Code = 331, CityName = "ورامين", ProvinceId = 7 },
                new() { Id = 332, Code = 332, CityName = "اردل", ProvinceId = 8 },
                new() { Id = 333, Code = 333, CityName = "آلوني", ProvinceId = 8 },
                new() { Id = 334, Code = 334, CityName = "باباحيدر", ProvinceId = 8 },
                new() { Id = 335, Code = 335, CityName = "بروجن", ProvinceId = 8 },
                new() { Id = 336, Code = 336, CityName = "بلداجي", ProvinceId = 8 },
                new() { Id = 337, Code = 337, CityName = "بن", ProvinceId = 8 },
                new() { Id = 338, Code = 338, CityName = "جونقان", ProvinceId = 8 },
                new() { Id = 339, Code = 339, CityName = "چلگرد", ProvinceId = 8 },
                new() { Id = 340, Code = 340, CityName = "سامان", ProvinceId = 8 },
                new() { Id = 341, Code = 341, CityName = "سفيددشت", ProvinceId = 8 },
                new() { Id = 342, Code = 342, CityName = "سودجان", ProvinceId = 8 },
                new() { Id = 343, Code = 343, CityName = "سورشجان", ProvinceId = 8 },
                new() { Id = 344, Code = 344, CityName = "شلمزار", ProvinceId = 8 },
                new() { Id = 345, Code = 345, CityName = "شهركرد", ProvinceId = 8 },
                new() { Id = 346, Code = 346, CityName = "طاقانك", ProvinceId = 8 },
                new() { Id = 347, Code = 347, CityName = "فارسان", ProvinceId = 8 },
                new() { Id = 348, Code = 348, CityName = "فرادنبه", ProvinceId = 8 },
                new() { Id = 349, Code = 349, CityName = "فرخ شهر", ProvinceId = 8 },
                new() { Id = 350, Code = 350, CityName = "كيان", ProvinceId = 8 },
                new() { Id = 351, Code = 351, CityName = "گندمان", ProvinceId = 8 },
                new() { Id = 352, Code = 352, CityName = "گهرو", ProvinceId = 8 },
                new() { Id = 353, Code = 353, CityName = "لردگان", ProvinceId = 8 },
                new() { Id = 354, Code = 354, CityName = "مال خليفه", ProvinceId = 8 },
                new() { Id = 355, Code = 355, CityName = "ناغان", ProvinceId = 8 },
                new() { Id = 356, Code = 356, CityName = "نافچ", ProvinceId = 8 },
                new() { Id = 357, Code = 357, CityName = "نقنه", ProvinceId = 8 },
                new() { Id = 358, Code = 358, CityName = "هفشجان", ProvinceId = 8 },
                new() { Id = 359, Code = 359, CityName = "ارسك", ProvinceId = 11 },
                new() { Id = 360, Code = 360, CityName = "اسديه", ProvinceId = 11 },
                new() { Id = 361, Code = 361, CityName = "اسفدن", ProvinceId = 11 },
                new() { Id = 362, Code = 362, CityName = "اسلاميه", ProvinceId = 11 },
                new() { Id = 363, Code = 363, CityName = "آرين شهر", ProvinceId = 11 },
                new() { Id = 364, Code = 364, CityName = "آيسك", ProvinceId = 11 },
                new() { Id = 365, Code = 365, CityName = "بشرويه", ProvinceId = 11 },
                new() { Id = 366, Code = 366, CityName = "بيرجند", ProvinceId = 11 },
                new() { Id = 367, Code = 367, CityName = "حاجي آباد", ProvinceId = 11 },
                new() { Id = 368, Code = 368, CityName = "خضري دشت بياض", ProvinceId = 11 },
                new() { Id = 369, Code = 369, CityName = "خوسف", ProvinceId = 11 },
                new() { Id = 370, Code = 370, CityName = "زهان", ProvinceId = 11 },
                new() { Id = 371, Code = 371, CityName = "سرايان", ProvinceId = 11 },
                new() { Id = 372, Code = 372, CityName = "سربيشه", ProvinceId = 11 },
                new() { Id = 373, Code = 373, CityName = "سه قلعه", ProvinceId = 11 },
                new() { Id = 374, Code = 374, CityName = "شوسف", ProvinceId = 11 },
                new() { Id = 375, Code = 375, CityName = "طبس مسينا", ProvinceId = 11 },
                new() { Id = 376, Code = 376, CityName = "فردوس", ProvinceId = 11 },
                new() { Id = 377, Code = 377, CityName = "قائن", ProvinceId = 11 },
                new() { Id = 378, Code = 378, CityName = "قهستان", ProvinceId = 11 },
                new() { Id = 379, Code = 379, CityName = "گزیک", ProvinceId = 11 },
                new() { Id = 380, Code = 380, CityName = "محمد شهر", ProvinceId = 11 },
                new() { Id = 381, Code = 381, CityName = "مود", ProvinceId = 11 },
                new() { Id = 382, Code = 382, CityName = "نهبندان", ProvinceId = 11 },
                new() { Id = 383, Code = 383, CityName = "نيمبلوک", ProvinceId = 11 },
                new() { Id = 384, Code = 384, CityName = "احمدآبادصولت", ProvinceId = 9 },
                new() { Id = 385, Code = 385, CityName = "انابد", ProvinceId = 9 },
                new() { Id = 386, Code = 386, CityName = "باجگيران", ProvinceId = 9 },
                new() { Id = 387, Code = 387, CityName = "باخرز", ProvinceId = 9 },
                new() { Id = 388, Code = 388, CityName = "بار", ProvinceId = 9 },
                new() { Id = 389, Code = 389, CityName = "بايگ", ProvinceId = 9 },
                new() { Id = 390, Code = 390, CityName = "بجستان", ProvinceId = 9 },
                new() { Id = 391, Code = 391, CityName = "بردسكن", ProvinceId = 9 },
                new() { Id = 392, Code = 392, CityName = "بيدخت", ProvinceId = 9 },
                new() { Id = 393, Code = 393, CityName = "تايباد", ProvinceId = 9 },
                new() { Id = 394, Code = 394, CityName = "تربت جام", ProvinceId = 9 },
                new() { Id = 395, Code = 395, CityName = "تربت حيدريه", ProvinceId = 9 },
                new() { Id = 396, Code = 396, CityName = "جغتاي", ProvinceId = 9 },
                new() { Id = 397, Code = 397, CityName = "جنگل", ProvinceId = 9 },
                new() { Id = 398, Code = 398, CityName = "چاپشلو", ProvinceId = 9 },
                new() { Id = 399, Code = 399, CityName = "چكنه", ProvinceId = 9 },
                new() { Id = 400, Code = 400, CityName = "چناران", ProvinceId = 9 },
                new() { Id = 401, Code = 401, CityName = "خرو", ProvinceId = 9 },
                new() { Id = 402, Code = 402, CityName = "خليل آباد", ProvinceId = 9 },
                new() { Id = 403, Code = 403, CityName = "خواف", ProvinceId = 9 },
                new() { Id = 404, Code = 404, CityName = "داورزن", ProvinceId = 9 },
                new() { Id = 405, Code = 405, CityName = "درگز", ProvinceId = 9 },
                new() { Id = 406, Code = 406, CityName = "درود", ProvinceId = 9 },
                new() { Id = 407, Code = 407, CityName = "دولت آباد ", ProvinceId = 9 },
                new() { Id = 408, Code = 408, CityName = "رباط سنگ", ProvinceId = 9 },
                new() { Id = 409, Code = 409, CityName = "رشتخوار", ProvinceId = 9 },
                new() { Id = 410, Code = 410, CityName = "رضويه", ProvinceId = 9 },
                new() { Id = 411, Code = 411, CityName = "روداب", ProvinceId = 9 },
                new() { Id = 412, Code = 412, CityName = "ريوش", ProvinceId = 9 },
                new() { Id = 413, Code = 413, CityName = "سبزوار", ProvinceId = 9 },
                new() { Id = 414, Code = 414, CityName = "سرخس", ProvinceId = 9 },
                new() { Id = 415, Code = 415, CityName = "سفيدسنگ", ProvinceId = 9 },
                new() { Id = 416, Code = 416, CityName = "سلامي", ProvinceId = 9 },
                new() { Id = 417, Code = 417, CityName = "سلطان آباد", ProvinceId = 9 },
                new() { Id = 418, Code = 418, CityName = "سنگان", ProvinceId = 9 },
                new() { Id = 419, Code = 419, CityName = "شادمهر", ProvinceId = 9 },
                new() { Id = 420, Code = 420, CityName = "شانديز", ProvinceId = 9 },
                new() { Id = 421, Code = 421, CityName = "ششتمد", ProvinceId = 9 },
                new() { Id = 422, Code = 422, CityName = "شهرآباد", ProvinceId = 9 },
                new() { Id = 423, Code = 423, CityName = "شهرزو", ProvinceId = 9 },
                new() { Id = 424, Code = 424, CityName = "صالح آباد  ", ProvinceId = 9 },
                new() { Id = 425, Code = 425, CityName = "طرقبه", ProvinceId = 9 },
                new() { Id = 426, Code = 426, CityName = "عشق آباد", ProvinceId = 9 },
                new() { Id = 427, Code = 427, CityName = "فرهادگرد", ProvinceId = 9 },
                new() { Id = 428, Code = 428, CityName = "فريمان", ProvinceId = 9 },
                new() { Id = 429, Code = 429, CityName = "فيروزه", ProvinceId = 9 },
                new() { Id = 430, Code = 430, CityName = "فيض آباد", ProvinceId = 9 },
                new() { Id = 431, Code = 431, CityName = "قاسم آباد", ProvinceId = 9 },
                new() { Id = 432, Code = 432, CityName = "قدمگاه", ProvinceId = 9 },
                new() { Id = 433, Code = 433, CityName = "قلندرآباد", ProvinceId = 9 },
                new() { Id = 434, Code = 434, CityName = "قوچان", ProvinceId = 9 },
                new() { Id = 435, Code = 435, CityName = "كاخك", ProvinceId = 9 },
                new() { Id = 436, Code = 436, CityName = "كاريز", ProvinceId = 9 },
                new() { Id = 437, Code = 437, CityName = "كاشمر", ProvinceId = 9 },
                new() { Id = 438, Code = 438, CityName = "كدكن", ProvinceId = 9 },
                new() { Id = 439, Code = 439, CityName = "كلات", ProvinceId = 9 },
                new() { Id = 440, Code = 440, CityName = "كندر", ProvinceId = 9 },
                new() { Id = 441, Code = 441, CityName = "گلمكان", ProvinceId = 9 },
                new() { Id = 442, Code = 442, CityName = "گناباد", ProvinceId = 9 },
                new() { Id = 443, Code = 443, CityName = "لطف آباد", ProvinceId = 9 },
                new() { Id = 444, Code = 444, CityName = "مزدآوند", ProvinceId = 9 },
                new() { Id = 445, Code = 445, CityName = "مشهد", ProvinceId = 9 },
                new() { Id = 446, Code = 446, CityName = "مشهدريزه", ProvinceId = 9 },
                new() { Id = 447, Code = 447, CityName = "ملك آباد", ProvinceId = 9 },
                new() { Id = 448, Code = 448, CityName = "نشتيفان", ProvinceId = 9 },
                new() { Id = 449, Code = 449, CityName = "نصر آباد", ProvinceId = 9 },
                new() { Id = 450, Code = 450, CityName = "نقاب", ProvinceId = 9 },
                new() { Id = 451, Code = 451, CityName = "نوخندان", ProvinceId = 9 },
                new() { Id = 452, Code = 452, CityName = "نيشابور", ProvinceId = 9 },
                new() { Id = 453, Code = 453, CityName = "نيل شهر", ProvinceId = 9 },
                new() { Id = 454, Code = 454, CityName = "همت آباد", ProvinceId = 9 },
                new() { Id = 455, Code = 455, CityName = "يونسي", ProvinceId = 9 },
                new() { Id = 456, Code = 456, CityName = "اسفراين", ProvinceId = 10 },
                new() { Id = 457, Code = 457, CityName = "ايور", ProvinceId = 10 },
                new() { Id = 458, Code = 458, CityName = "آشخانه", ProvinceId = 10 },
                new() { Id = 459, Code = 459, CityName = "بجنورد", ProvinceId = 10 },
                new() { Id = 460, Code = 460, CityName = "پيش قلعه", ProvinceId = 10 },
                new() { Id = 461, Code = 461, CityName = "تيتكانلو", ProvinceId = 10 },
                new() { Id = 462, Code = 462, CityName = "جاجرم", ProvinceId = 10 },
                new() { Id = 463, Code = 463, CityName = "حصارگرمخان", ProvinceId = 10 },
                new() { Id = 464, Code = 464, CityName = "درق", ProvinceId = 10 },
                new() { Id = 465, Code = 465, CityName = "راز", ProvinceId = 10 },
                new() { Id = 466, Code = 466, CityName = "سنخواست", ProvinceId = 10 },
                new() { Id = 467, Code = 467, CityName = "شوقان", ProvinceId = 10 },
                new() { Id = 468, Code = 468, CityName = "شيروان", ProvinceId = 10 },
                new() { Id = 469, Code = 469, CityName = "صفي آباد", ProvinceId = 10 },
                new() { Id = 470, Code = 470, CityName = "فاروج", ProvinceId = 10 },
                new() { Id = 471, Code = 471, CityName = "قاضي", ProvinceId = 10 },
                new() { Id = 472, Code = 472, CityName = "گرمه", ProvinceId = 10 },
                new() { Id = 473, Code = 473, CityName = "لوجلي", ProvinceId = 10 },
                new() { Id = 474, Code = 474, CityName = "اروندكنار", ProvinceId = 12 },
                new() { Id = 475, Code = 475, CityName = "الوان", ProvinceId = 12 },
                new() { Id = 476, Code = 476, CityName = "اميديه", ProvinceId = 12 },
                new() { Id = 477, Code = 477, CityName = "انديمشك", ProvinceId = 12 },
                new() { Id = 478, Code = 478, CityName = "اهواز", ProvinceId = 12 },
                new() { Id = 479, Code = 479, CityName = "ايذه", ProvinceId = 12 },
                new() { Id = 480, Code = 480, CityName = "آبادان", ProvinceId = 12 },
                new() { Id = 481, Code = 481, CityName = "آغاجاري", ProvinceId = 12 },
                new() { Id = 482, Code = 482, CityName = "باغ ملك", ProvinceId = 12 },
                new() { Id = 483, Code = 483, CityName = "بستان", ProvinceId = 12 },
                new() { Id = 484, Code = 484, CityName = "بندرامام خميني", ProvinceId = 12 },
                new() { Id = 485, Code = 485, CityName = "بندرماهشهر", ProvinceId = 12 },
                new() { Id = 486, Code = 486, CityName = "بهبهان", ProvinceId = 12 },
                new() { Id = 487, Code = 487, CityName = "تركالكي", ProvinceId = 12 },
                new() { Id = 488, Code = 488, CityName = "جايزان", ProvinceId = 12 },
                new() { Id = 489, Code = 489, CityName = "جنت مكان", ProvinceId = 12 },
                new() { Id = 490, Code = 490, CityName = "چغاميش", ProvinceId = 12 },
                new() { Id = 491, Code = 491, CityName = "چمران", ProvinceId = 12 },
                new() { Id = 492, Code = 492, CityName = "چوئبده", ProvinceId = 12 },
                new() { Id = 493, Code = 493, CityName = "حر", ProvinceId = 12 },
                new() { Id = 494, Code = 494, CityName = "حسينيه", ProvinceId = 12 },
                new() { Id = 495, Code = 495, CityName = "حمزه", ProvinceId = 12 },
                new() { Id = 496, Code = 496, CityName = "حميديه", ProvinceId = 12 },
                new() { Id = 497, Code = 497, CityName = "خرمشهر", ProvinceId = 12 },
                new() { Id = 498, Code = 498, CityName = "دارخوين", ProvinceId = 12 },
                new() { Id = 499, Code = 499, CityName = "دزآب", ProvinceId = 12 },
                new() { Id = 500, Code = 500, CityName = "دزفول", ProvinceId = 12 },
                new() { Id = 501, Code = 501, CityName = "دهدز", ProvinceId = 12 },
                new() { Id = 502, Code = 502, CityName = "رامشير", ProvinceId = 12 },
                new() { Id = 503, Code = 503, CityName = "رامهرمز", ProvinceId = 12 },
                new() { Id = 504, Code = 504, CityName = "رفيع", ProvinceId = 12 },
                new() { Id = 505, Code = 505, CityName = "زهره", ProvinceId = 12 },
                new() { Id = 506, Code = 506, CityName = "سالند", ProvinceId = 12 },
                new() { Id = 507, Code = 507, CityName = "سردشت ", ProvinceId = 12 },
                new() { Id = 508, Code = 508, CityName = "سماله", ProvinceId = 12 },
                new() { Id = 509, Code = 509, CityName = "سوسنگرد", ProvinceId = 12 },
                new() { Id = 510, Code = 510, CityName = "شادگان", ProvinceId = 12 },
                new() { Id = 511, Code = 511, CityName = "شاوور", ProvinceId = 12 },
                new() { Id = 512, Code = 512, CityName = "شرافت", ProvinceId = 12 },
                new() { Id = 513, Code = 513, CityName = "شوش", ProvinceId = 12 },
                new() { Id = 514, Code = 514, CityName = "شوشتر", ProvinceId = 12 },
                new() { Id = 515, Code = 515, CityName = "شيبان", ProvinceId = 12 },
                new() { Id = 516, Code = 516, CityName = "صالح شهر", ProvinceId = 12 },
                new() { Id = 517, Code = 517, CityName = "صالح مشطط", ProvinceId = 12 },
                new() { Id = 518, Code = 518, CityName = "صفي آباد ", ProvinceId = 12 },
                new() { Id = 519, Code = 519, CityName = "صيدون", ProvinceId = 12 },
                new() { Id = 520, Code = 520, CityName = "قلعه تل", ProvinceId = 12 },
                new() { Id = 521, Code = 521, CityName = "قلعه خواجه", ProvinceId = 12 },
                new() { Id = 522, Code = 522, CityName = "گتوند", ProvinceId = 12 },
                new() { Id = 523, Code = 523, CityName = "گوريه", ProvinceId = 12 },
                new() { Id = 524, Code = 524, CityName = "لالي", ProvinceId = 12 },
                new() { Id = 525, Code = 525, CityName = "مسجدسليمان", ProvinceId = 12 },
                new() { Id = 526, Code = 526, CityName = "مشراگه", ProvinceId = 12 },
                new() { Id = 527, Code = 527, CityName = "مقاومت", ProvinceId = 12 },
                new() { Id = 528, Code = 528, CityName = "ملاثاني", ProvinceId = 12 },
                new() { Id = 529, Code = 529, CityName = "ميانرود", ProvinceId = 12 },
                new() { Id = 530, Code = 530, CityName = "ميداود", ProvinceId = 12 },
                new() { Id = 531, Code = 531, CityName = "مينوشهر", ProvinceId = 12 },
                new() { Id = 532, Code = 532, CityName = "ويس", ProvinceId = 12 },
                new() { Id = 533, Code = 533, CityName = "هفتگل", ProvinceId = 12 },
                new() { Id = 534, Code = 534, CityName = "هنديجان", ProvinceId = 12 },
                new() { Id = 535, Code = 535, CityName = "هويزه", ProvinceId = 12 },
                new() { Id = 536, Code = 536, CityName = "ابهر", ProvinceId = 13 },
                new() { Id = 537, Code = 537, CityName = "ارمغانخانه", ProvinceId = 13 },
                new() { Id = 538, Code = 538, CityName = "آب بر", ProvinceId = 13 },
                new() { Id = 539, Code = 539, CityName = "چورزق", ProvinceId = 13 },
                new() { Id = 540, Code = 540, CityName = "حلب", ProvinceId = 13 },
                new() { Id = 541, Code = 541, CityName = "خرمدره", ProvinceId = 13 },
                new() { Id = 542, Code = 542, CityName = "دندي", ProvinceId = 13 },
                new() { Id = 543, Code = 543, CityName = "زرين آباد", ProvinceId = 13 },
                new() { Id = 544, Code = 544, CityName = "زرين رود", ProvinceId = 13 },
                new() { Id = 545, Code = 545, CityName = "زنجان", ProvinceId = 13 },
                new() { Id = 546, Code = 546, CityName = "سجاس", ProvinceId = 13 },
                new() { Id = 547, Code = 547, CityName = "سلطانيه", ProvinceId = 13 },
                new() { Id = 548, Code = 548, CityName = "سهرورد", ProvinceId = 13 },
                new() { Id = 549, Code = 549, CityName = "صائين قلعه", ProvinceId = 13 },
                new() { Id = 550, Code = 550, CityName = "قيدار", ProvinceId = 13 },
                new() { Id = 551, Code = 551, CityName = "گرماب", ProvinceId = 13 },
                new() { Id = 552, Code = 552, CityName = "ماه نشان", ProvinceId = 13 },
                new() { Id = 553, Code = 553, CityName = "هيدج", ProvinceId = 13 },
                new() { Id = 554, Code = 554, CityName = "اميريه", ProvinceId = 14 },
                new() { Id = 555, Code = 555, CityName = "ايوانكي", ProvinceId = 14 },
                new() { Id = 556, Code = 556, CityName = "آرادان", ProvinceId = 14 },
                new() { Id = 557, Code = 557, CityName = "بسطام", ProvinceId = 14 },
                new() { Id = 558, Code = 558, CityName = "بيارجمند", ProvinceId = 14 },
                new() { Id = 559, Code = 559, CityName = "دامغان", ProvinceId = 14 },
                new() { Id = 560, Code = 560, CityName = "درجزين", ProvinceId = 14 },
                new() { Id = 561, Code = 561, CityName = "ديباج", ProvinceId = 14 },
                new() { Id = 562, Code = 562, CityName = "سرخه", ProvinceId = 14 },
                new() { Id = 563, Code = 563, CityName = "سمنان", ProvinceId = 14 },
                new() { Id = 564, Code = 564, CityName = "شاهرود", ProvinceId = 14 },
                new() { Id = 565, Code = 565, CityName = "شهميرزاد", ProvinceId = 14 },
                new() { Id = 566, Code = 566, CityName = "كلاته خيج", ProvinceId = 14 },
                new() { Id = 567, Code = 567, CityName = "گرمسار", ProvinceId = 14 },
                new() { Id = 568, Code = 568, CityName = "مجن", ProvinceId = 14 },
                new() { Id = 569, Code = 569, CityName = "مهدي شهر", ProvinceId = 14 },
                new() { Id = 570, Code = 570, CityName = "ميامي", ProvinceId = 14 },
                new() { Id = 571, Code = 571, CityName = "اديمي", ProvinceId = 15 },
                new() { Id = 572, Code = 572, CityName = "اسپكه", ProvinceId = 15 },
                new() { Id = 573, Code = 573, CityName = "ايرانشهر", ProvinceId = 15 },
                new() { Id = 574, Code = 574, CityName = "بزمان", ProvinceId = 15 },
                new() { Id = 575, Code = 575, CityName = "بمپور", ProvinceId = 15 },
                new() { Id = 576, Code = 576, CityName = "بنت", ProvinceId = 15 },
                new() { Id = 577, Code = 577, CityName = "بنجار", ProvinceId = 15 },
                new() { Id = 578, Code = 578, CityName = "پيشين", ProvinceId = 15 },
                new() { Id = 579, Code = 579, CityName = "جالق", ProvinceId = 15 },
                new() { Id = 580, Code = 580, CityName = "چاه بهار", ProvinceId = 15 },
                new() { Id = 581, Code = 581, CityName = "خاش", ProvinceId = 15 },
                new() { Id = 582, Code = 582, CityName = "دوست محمد", ProvinceId = 15 },
                new() { Id = 583, Code = 583, CityName = "راسك", ProvinceId = 15 },
                new() { Id = 584, Code = 584, CityName = "زابل", ProvinceId = 15 },
                new() { Id = 585, Code = 585, CityName = "زابلي", ProvinceId = 15 },
                new() { Id = 586, Code = 586, CityName = "زاهدان", ProvinceId = 15 },
                new() { Id = 587, Code = 587, CityName = "زرآباد", ProvinceId = 15 },
                new() { Id = 588, Code = 588, CityName = "زهك", ProvinceId = 15 },
                new() { Id = 589, Code = 589, CityName = "سراوان", ProvinceId = 15 },
                new() { Id = 590, Code = 590, CityName = "سرباز", ProvinceId = 15 },
                new() { Id = 591, Code = 591, CityName = "سوران", ProvinceId = 15 },
                new() { Id = 592, Code = 592, CityName = "سيركان", ProvinceId = 15 },
                new() { Id = 593, Code = 593, CityName = "علي اكبر", ProvinceId = 15 },
                new() { Id = 594, Code = 594, CityName = "فنوج", ProvinceId = 15 },
                new() { Id = 595, Code = 595, CityName = "قصرقند", ProvinceId = 15 },
                new() { Id = 596, Code = 596, CityName = "كنارك", ProvinceId = 15 },
                new() { Id = 597, Code = 597, CityName = "گشت", ProvinceId = 15 },
                new() { Id = 598, Code = 598, CityName = "گلمورتي", ProvinceId = 15 },
                new() { Id = 599, Code = 599, CityName = "محمدان", ProvinceId = 15 },
                new() { Id = 600, Code = 600, CityName = "محمد آباد", ProvinceId = 15 },
                new() { Id = 601, Code = 601, CityName = "محمدي", ProvinceId = 15 },
                new() { Id = 602, Code = 602, CityName = "ميرجاوه", ProvinceId = 15 },
                new() { Id = 603, Code = 603, CityName = "نصرت آباد", ProvinceId = 15 },
                new() { Id = 604, Code = 604, CityName = "نگور", ProvinceId = 15 },
                new() { Id = 605, Code = 605, CityName = "نوك آباد", ProvinceId = 15 },
                new() { Id = 606, Code = 606, CityName = "نيك شهر", ProvinceId = 15 },
                new() { Id = 607, Code = 607, CityName = "هيدوج", ProvinceId = 15 },
                new() { Id = 608, Code = 608, CityName = "اردكان", ProvinceId = 16 },
                new() { Id = 609, Code = 609, CityName = "ارسنجان", ProvinceId = 16 },
                new() { Id = 610, Code = 610, CityName = "استهبان", ProvinceId = 16 },
                new() { Id = 611, Code = 611, CityName = "اسير", ProvinceId = 16 },
                new() { Id = 612, Code = 612, CityName = "اشكنان", ProvinceId = 16 },
                new() { Id = 613, Code = 613, CityName = "افزر", ProvinceId = 16 },
                new() { Id = 614, Code = 614, CityName = "اقليد", ProvinceId = 16 },
                new() { Id = 615, Code = 615, CityName = "امام شهر", ProvinceId = 16 },
                new() { Id = 616, Code = 616, CityName = "اوز", ProvinceId = 16 },
                new() { Id = 617, Code = 617, CityName = "اهل", ProvinceId = 16 },
                new() { Id = 618, Code = 618, CityName = "ايج", ProvinceId = 16 },
                new() { Id = 619, Code = 619, CityName = "ايزدخواست", ProvinceId = 16 },
                new() { Id = 620, Code = 620, CityName = "آباده", ProvinceId = 16 },
                new() { Id = 621, Code = 621, CityName = "آباده طشك", ProvinceId = 16 },
                new() { Id = 622, Code = 622, CityName = "باب انار", ProvinceId = 16 },
                new() { Id = 623, Code = 623, CityName = "بالاده", ProvinceId = 16 },
                new() { Id = 624, Code = 624, CityName = "بنارويه", ProvinceId = 16 },
                new() { Id = 625, Code = 625, CityName = "بوانات", ProvinceId = 16 },
                new() { Id = 626, Code = 626, CityName = "بهمن", ProvinceId = 16 },
                new() { Id = 627, Code = 627, CityName = "بيرم", ProvinceId = 16 },
                new() { Id = 628, Code = 628, CityName = "بيضا", ProvinceId = 16 },
                new() { Id = 629, Code = 629, CityName = "جنت شهر", ProvinceId = 16 },
                new() { Id = 630, Code = 630, CityName = "جويم", ProvinceId = 16 },
                new() { Id = 631, Code = 631, CityName = "جهرم", ProvinceId = 16 },
                new() { Id = 632, Code = 632, CityName = "حاجي آباد ", ProvinceId = 16 },
                new() { Id = 633, Code = 633, CityName = "حسامي", ProvinceId = 16 },
                new() { Id = 634, Code = 634, CityName = "حسن آباد  ", ProvinceId = 16 },
                new() { Id = 635, Code = 635, CityName = "خانه زنيان", ProvinceId = 16 },
                new() { Id = 636, Code = 636, CityName = "خاوران", ProvinceId = 16 },
                new() { Id = 637, Code = 637, CityName = "خرامه", ProvinceId = 16 },
                new() { Id = 638, Code = 638, CityName = "خشت", ProvinceId = 16 },
                new() { Id = 639, Code = 639, CityName = "خنج", ProvinceId = 16 },
                new() { Id = 640, Code = 640, CityName = "خور ", ProvinceId = 16 },
                new() { Id = 641, Code = 641, CityName = "خومه زار", ProvinceId = 16 },
                new() { Id = 642, Code = 642, CityName = "داراب", ProvinceId = 16 },
                new() { Id = 643, Code = 643, CityName = "داريان", ProvinceId = 16 },
                new() { Id = 644, Code = 644, CityName = "دبيران", ProvinceId = 16 },
                new() { Id = 645, Code = 645, CityName = "دژكرد", ProvinceId = 16 },
                new() { Id = 646, Code = 646, CityName = "دوبرجي", ProvinceId = 16 },
                new() { Id = 647, Code = 647, CityName = "دوزه", ProvinceId = 16 },
                new() { Id = 648, Code = 648, CityName = "دهرم", ProvinceId = 16 },
                new() { Id = 649, Code = 649, CityName = "رامجرد", ProvinceId = 16 },
                new() { Id = 650, Code = 650, CityName = "رونيز", ProvinceId = 16 },
                new() { Id = 651, Code = 651, CityName = "زاهدشهر", ProvinceId = 16 },
                new() { Id = 652, Code = 652, CityName = "زرقان", ProvinceId = 16 },
                new() { Id = 653, Code = 653, CityName = "سده", ProvinceId = 16 },
                new() { Id = 654, Code = 654, CityName = "سروستان", ProvinceId = 16 },
                new() { Id = 655, Code = 655, CityName = "سعادت شهر", ProvinceId = 16 },
                new() { Id = 656, Code = 656, CityName = "سورمق", ProvinceId = 16 },
                new() { Id = 657, Code = 657, CityName = "سيدان", ProvinceId = 16 },
                new() { Id = 658, Code = 658, CityName = "ششده", ProvinceId = 16 },
                new() { Id = 659, Code = 659, CityName = "شهر جديد صدرا", ProvinceId = 16 },
                new() { Id = 660, Code = 660, CityName = "شهرپير", ProvinceId = 16 },
                new() { Id = 661, Code = 661, CityName = "شيراز", ProvinceId = 16 },
                new() { Id = 662, Code = 662, CityName = "صغاد", ProvinceId = 16 },
                new() { Id = 663, Code = 663, CityName = "صفاشهر", ProvinceId = 16 },
                new() { Id = 664, Code = 664, CityName = "علامرودشت", ProvinceId = 16 },
                new() { Id = 665, Code = 665, CityName = "عمادده", ProvinceId = 16 },
                new() { Id = 666, Code = 666, CityName = "فدامي", ProvinceId = 16 },
                new() { Id = 667, Code = 667, CityName = "فراشبند", ProvinceId = 16 },
                new() { Id = 668, Code = 668, CityName = "فسا", ProvinceId = 16 },
                new() { Id = 669, Code = 669, CityName = "فيروزآباد", ProvinceId = 16 },
                new() { Id = 670, Code = 670, CityName = "قادرآباد", ProvinceId = 16 },
                new() { Id = 671, Code = 671, CityName = "قائميه", ProvinceId = 16 },
                new() { Id = 672, Code = 672, CityName = "قطب آباد", ProvinceId = 16 },
                new() { Id = 673, Code = 673, CityName = "قطرويه", ProvinceId = 16 },
                new() { Id = 674, Code = 674, CityName = "قير", ProvinceId = 16 },
                new() { Id = 675, Code = 675, CityName = "كارزين", ProvinceId = 16 },
                new() { Id = 676, Code = 676, CityName = "كازرون", ProvinceId = 16 },
                new() { Id = 677, Code = 677, CityName = "كامفيروز", ProvinceId = 16 },
                new() { Id = 678, Code = 678, CityName = "كره اي", ProvinceId = 16 },
                new() { Id = 679, Code = 679, CityName = "كنارتخته", ProvinceId = 16 },
                new() { Id = 680, Code = 680, CityName = "كوار", ProvinceId = 16 },
                new() { Id = 681, Code = 681, CityName = "كوهنجان", ProvinceId = 16 },
                new() { Id = 682, Code = 682, CityName = "گراش", ProvinceId = 16 },
                new() { Id = 683, Code = 683, CityName = "گله دار", ProvinceId = 16 },
                new() { Id = 684, Code = 684, CityName = "لار", ProvinceId = 16 },
                new() { Id = 685, Code = 685, CityName = "لامرد", ProvinceId = 16 },
                new() { Id = 686, Code = 686, CityName = "لپوئي", ProvinceId = 16 },
                new() { Id = 687, Code = 687, CityName = "لطيفي", ProvinceId = 16 },
                new() { Id = 688, Code = 688, CityName = "مبارك آباد", ProvinceId = 16 },
                new() { Id = 689, Code = 689, CityName = "مرودشت", ProvinceId = 16 },
                new() { Id = 690, Code = 690, CityName = "مشكان", ProvinceId = 16 },
                new() { Id = 691, Code = 691, CityName = "مصيري", ProvinceId = 16 },
                new() { Id = 692, Code = 692, CityName = "مهر", ProvinceId = 16 },
                new() { Id = 693, Code = 693, CityName = "ميمند", ProvinceId = 16 },
                new() { Id = 694, Code = 694, CityName = "نوبندگان", ProvinceId = 16 },
                new() { Id = 695, Code = 695, CityName = "نوجين", ProvinceId = 16 },
                new() { Id = 696, Code = 696, CityName = "نودان", ProvinceId = 16 },
                new() { Id = 697, Code = 697, CityName = "نورآباد", ProvinceId = 16 },
                new() { Id = 698, Code = 698, CityName = "ني ريز", ProvinceId = 16 },
                new() { Id = 699, Code = 699, CityName = "وراوي", ProvinceId = 16 },
                new() { Id = 700, Code = 700, CityName = "هماشهر", ProvinceId = 16 },
                new() { Id = 701, Code = 701, CityName = "ارداق", ProvinceId = 17 },
                new() { Id = 702, Code = 702, CityName = "اسفرورين", ProvinceId = 17 },
                new() { Id = 703, Code = 703, CityName = "اقباليه", ProvinceId = 17 },
                new() { Id = 704, Code = 704, CityName = "الوند", ProvinceId = 17 },
                new() { Id = 705, Code = 705, CityName = "آبگرم", ProvinceId = 17 },
                new() { Id = 706, Code = 706, CityName = "آبيك", ProvinceId = 17 },
                new() { Id = 707, Code = 707, CityName = "آوج", ProvinceId = 17 },
                new() { Id = 708, Code = 708, CityName = "بوئين زهرا", ProvinceId = 17 },
                new() { Id = 709, Code = 709, CityName = "بيدستان", ProvinceId = 17 },
                new() { Id = 710, Code = 710, CityName = "تاكستان", ProvinceId = 17 },
                new() { Id = 711, Code = 711, CityName = "خاكعلي", ProvinceId = 17 },
                new() { Id = 712, Code = 712, CityName = "خرمدشت", ProvinceId = 17 },
                new() { Id = 713, Code = 713, CityName = "دانسفهان", ProvinceId = 17 },
                new() { Id = 714, Code = 714, CityName = "رازميان", ProvinceId = 17 },
                new() { Id = 715, Code = 715, CityName = "سگزآباد", ProvinceId = 17 },
                new() { Id = 716, Code = 716, CityName = "سيردان", ProvinceId = 17 },
                new() { Id = 717, Code = 717, CityName = "شال", ProvinceId = 17 },
                new() { Id = 718, Code = 718, CityName = "شريفيه", ProvinceId = 17 },
                new() { Id = 719, Code = 719, CityName = "ضياءآباد", ProvinceId = 17 },
                new() { Id = 720, Code = 720, CityName = "قزوين", ProvinceId = 17 },
                new() { Id = 721, Code = 721, CityName = "كوهين", ProvinceId = 17 },
                new() { Id = 722, Code = 722, CityName = "محمديه", ProvinceId = 17 },
                new() { Id = 723, Code = 723, CityName = "محمودآبادنمونه", ProvinceId = 17 },
                new() { Id = 724, Code = 724, CityName = "معلم كلايه", ProvinceId = 17 },
                new() { Id = 725, Code = 725, CityName = "نرجه", ProvinceId = 17 },
                new() { Id = 726, Code = 726, CityName = "جعفريه", ProvinceId = 18 },
                new() { Id = 727, Code = 727, CityName = "دستجرد", ProvinceId = 18 },
                new() { Id = 728, Code = 728, CityName = "سلفچگان", ProvinceId = 18 },
                new() { Id = 729, Code = 729, CityName = "قم", ProvinceId = 18 },
                new() { Id = 730, Code = 730, CityName = "قنوات", ProvinceId = 18 },
                new() { Id = 731, Code = 731, CityName = "كهك", ProvinceId = 18 },
                new() { Id = 732, Code = 732, CityName = "آرمرده", ProvinceId = 19 },
                new() { Id = 733, Code = 733, CityName = "بابارشاني", ProvinceId = 19 },
                new() { Id = 734, Code = 734, CityName = "بانه", ProvinceId = 19 },
                new() { Id = 735, Code = 735, CityName = "بلبان آباد", ProvinceId = 19 },
                new() { Id = 736, Code = 736, CityName = "بوئين سفلي", ProvinceId = 19 },
                new() { Id = 737, Code = 737, CityName = "بيجار", ProvinceId = 19 },
                new() { Id = 738, Code = 738, CityName = "چناره", ProvinceId = 19 },
                new() { Id = 739, Code = 739, CityName = "دزج", ProvinceId = 19 },
                new() { Id = 740, Code = 740, CityName = "دلبران", ProvinceId = 19 },
                new() { Id = 741, Code = 741, CityName = "دهگلان", ProvinceId = 19 },
                new() { Id = 742, Code = 742, CityName = "ديواندره", ProvinceId = 19 },
                new() { Id = 743, Code = 743, CityName = "زرينه", ProvinceId = 19 },
                new() { Id = 744, Code = 744, CityName = "سروآباد", ProvinceId = 19 },
                new() { Id = 745, Code = 745, CityName = "سريش آباد", ProvinceId = 19 },
                new() { Id = 746, Code = 746, CityName = "سقز", ProvinceId = 19 },
                new() { Id = 747, Code = 747, CityName = "سنندج", ProvinceId = 19 },
                new() { Id = 748, Code = 748, CityName = "شويشه", ProvinceId = 19 },
                new() { Id = 749, Code = 749, CityName = "صاحب", ProvinceId = 19 },
                new() { Id = 750, Code = 750, CityName = "قروه", ProvinceId = 19 },
                new() { Id = 751, Code = 751, CityName = "كامياران", ProvinceId = 19 },
                new() { Id = 752, Code = 752, CityName = "كاني دينار", ProvinceId = 19 },
                new() { Id = 753, Code = 753, CityName = "كاني سور", ProvinceId = 19 },
                new() { Id = 754, Code = 754, CityName = "مريوان", ProvinceId = 19 },
                new() { Id = 755, Code = 755, CityName = "موچش", ProvinceId = 19 },
                new() { Id = 756, Code = 756, CityName = "ياسوكند", ProvinceId = 19 },
                new() { Id = 757, Code = 757, CityName = "اختيارآباد", ProvinceId = 20 },
                new() { Id = 758, Code = 758, CityName = "ارزوئيه", ProvinceId = 20 },
                new() { Id = 759, Code = 759, CityName = "امين شهر", ProvinceId = 20 },
                new() { Id = 760, Code = 760, CityName = "انار", ProvinceId = 20 },
                new() { Id = 761, Code = 761, CityName = "اندوهجرد", ProvinceId = 20 },
                new() { Id = 762, Code = 762, CityName = "باغين", ProvinceId = 20 },
                new() { Id = 763, Code = 763, CityName = "بافت", ProvinceId = 20 },
                new() { Id = 764, Code = 764, CityName = "بردسير", ProvinceId = 20 },
                new() { Id = 765, Code = 765, CityName = "بروات", ProvinceId = 20 },
                new() { Id = 766, Code = 766, CityName = "بزنجان", ProvinceId = 20 },
                new() { Id = 767, Code = 767, CityName = "بم", ProvinceId = 20 },
                new() { Id = 768, Code = 768, CityName = "بهرمان", ProvinceId = 20 },
                new() { Id = 769, Code = 769, CityName = "پاريز", ProvinceId = 20 },
                new() { Id = 770, Code = 770, CityName = "جبالبارز", ProvinceId = 20 },
                new() { Id = 771, Code = 771, CityName = "جوپار", ProvinceId = 20 },
                new() { Id = 772, Code = 772, CityName = "جوزم", ProvinceId = 20 },
                new() { Id = 773, Code = 773, CityName = "جيرفت", ProvinceId = 20 },
                new() { Id = 774, Code = 774, CityName = "چترود", ProvinceId = 20 },
                new() { Id = 775, Code = 775, CityName = "خاتون آباد", ProvinceId = 20 },
                new() { Id = 776, Code = 776, CityName = "خانوك", ProvinceId = 20 },
                new() { Id = 777, Code = 777, CityName = "خورسند", ProvinceId = 20 },
                new() { Id = 778, Code = 778, CityName = "درب بهشت", ProvinceId = 20 },
                new() { Id = 779, Code = 779, CityName = "دوساري", ProvinceId = 20 },
                new() { Id = 780, Code = 780, CityName = "دهج", ProvinceId = 20 },
                new() { Id = 781, Code = 781, CityName = "رابر", ProvinceId = 20 },
                new() { Id = 782, Code = 782, CityName = "راور", ProvinceId = 20 },
                new() { Id = 783, Code = 783, CityName = "راين", ProvinceId = 20 },
                new() { Id = 784, Code = 784, CityName = "رفسنجان", ProvinceId = 20 },
                new() { Id = 785, Code = 785, CityName = "رودبار", ProvinceId = 20 },
                new() { Id = 786, Code = 786, CityName = "ريحان شهر", ProvinceId = 20 },
                new() { Id = 787, Code = 787, CityName = "زرند", ProvinceId = 20 },
                new() { Id = 788, Code = 788, CityName = "زنگي آباد", ProvinceId = 20 },
                new() { Id = 789, Code = 789, CityName = "زيدآباد", ProvinceId = 20 },
                new() { Id = 790, Code = 790, CityName = "سرچشمه", ProvinceId = 20 },
                new() { Id = 791, Code = 791, CityName = "سيرجان", ProvinceId = 20 },
                new() { Id = 792, Code = 792, CityName = "شهداد", ProvinceId = 20 },
                new() { Id = 793, Code = 793, CityName = "شهربابك", ProvinceId = 20 },
                new() { Id = 794, Code = 794, CityName = "صفائيه", ProvinceId = 20 },
                new() { Id = 795, Code = 795, CityName = "عنبرآباد", ProvinceId = 20 },
                new() { Id = 796, Code = 796, CityName = "فارياب", ProvinceId = 20 },
                new() { Id = 797, Code = 797, CityName = "فهرج", ProvinceId = 20 },
                new() { Id = 798, Code = 798, CityName = "قلعه گنج", ProvinceId = 20 },
                new() { Id = 799, Code = 799, CityName = "كاظم آباد", ProvinceId = 20 },
                new() { Id = 800, Code = 800, CityName = "كرمان", ProvinceId = 20 },
                new() { Id = 801, Code = 801, CityName = "كشكوئيه", ProvinceId = 20 },
                new() { Id = 802, Code = 802, CityName = "كوهبنان", ProvinceId = 20 },
                new() { Id = 803, Code = 803, CityName = "كهنوج", ProvinceId = 20 },
                new() { Id = 804, Code = 804, CityName = "كيانشهر", ProvinceId = 20 },
                new() { Id = 805, Code = 805, CityName = "گلباف", ProvinceId = 20 },
                new() { Id = 806, Code = 806, CityName = "گلزار", ProvinceId = 20 },
                new() { Id = 807, Code = 807, CityName = "لاله زار", ProvinceId = 20 },
                new() { Id = 808, Code = 808, CityName = "ماهان", ProvinceId = 20 },
                new() { Id = 809, Code = 809, CityName = "محمد آباد ", ProvinceId = 20 },
                new() { Id = 810, Code = 810, CityName = "محي آباد", ProvinceId = 20 },
                new() { Id = 811, Code = 811, CityName = "مردهك", ProvinceId = 20 },
                new() { Id = 812, Code = 812, CityName = "منوجان", ProvinceId = 20 },
                new() { Id = 813, Code = 813, CityName = "نجف شهر", ProvinceId = 20 },
                new() { Id = 814, Code = 814, CityName = "نرماشير", ProvinceId = 20 },
                new() { Id = 815, Code = 815, CityName = "نظام شهر", ProvinceId = 20 },
                new() { Id = 816, Code = 816, CityName = "نگار", ProvinceId = 20 },
                new() { Id = 817, Code = 817, CityName = "نودژ", ProvinceId = 20 },
                new() { Id = 818, Code = 818, CityName = "هجدك", ProvinceId = 20 },
                new() { Id = 819, Code = 819, CityName = "هماشهر ", ProvinceId = 20 },
                new() { Id = 820, Code = 820, CityName = "يزدان شهر", ProvinceId = 20 },
                new() { Id = 821, Code = 821, CityName = "ازگله", ProvinceId = 21 },
                new() { Id = 822, Code = 822, CityName = "اسلام آبادغرب", ProvinceId = 21 },
                new() { Id = 823, Code = 823, CityName = "باينگان", ProvinceId = 21 },
                new() { Id = 824, Code = 824, CityName = "بيستون", ProvinceId = 21 },
                new() { Id = 825, Code = 825, CityName = "پاوه", ProvinceId = 21 },
                new() { Id = 826, Code = 826, CityName = "تازه آباد", ProvinceId = 21 },
                new() { Id = 827, Code = 827, CityName = "جوانرود", ProvinceId = 21 },
                new() { Id = 828, Code = 828, CityName = "حميل", ProvinceId = 21 },
                new() { Id = 829, Code = 829, CityName = "رباط", ProvinceId = 21 },
                new() { Id = 830, Code = 830, CityName = "روانسر", ProvinceId = 21 },
                new() { Id = 831, Code = 831, CityName = "سرپل ذهاب", ProvinceId = 21 },
                new() { Id = 832, Code = 832, CityName = "سرمست", ProvinceId = 21 },
                new() { Id = 833, Code = 833, CityName = "سطر", ProvinceId = 21 },
                new() { Id = 834, Code = 834, CityName = "سنقر", ProvinceId = 21 },
                new() { Id = 835, Code = 835, CityName = "سومار", ProvinceId = 21 },
                new() { Id = 836, Code = 836, CityName = "شاهو", ProvinceId = 21 },
                new() { Id = 837, Code = 837, CityName = "صحنه", ProvinceId = 21 },
                new() { Id = 838, Code = 838, CityName = "قصرشيرين", ProvinceId = 21 },
                new() { Id = 839, Code = 839, CityName = "كرمانشاه", ProvinceId = 21 },
                new() { Id = 840, Code = 840, CityName = "كرندغرب", ProvinceId = 21 },
                new() { Id = 841, Code = 841, CityName = "كنگاور", ProvinceId = 21 },
                new() { Id = 842, Code = 842, CityName = "كوزران", ProvinceId = 21 },
                new() { Id = 843, Code = 843, CityName = "گهواره", ProvinceId = 21 },
                new() { Id = 844, Code = 844, CityName = "گيلانغرب", ProvinceId = 21 },
                new() { Id = 845, Code = 845, CityName = "ميان راهان", ProvinceId = 21 },
                new() { Id = 846, Code = 846, CityName = "نودشه", ProvinceId = 21 },
                new() { Id = 847, Code = 847, CityName = "نوسود", ProvinceId = 21 },
                new() { Id = 848, Code = 848, CityName = "هرسين", ProvinceId = 21 },
                new() { Id = 849, Code = 849, CityName = "هلشي", ProvinceId = 21 },
                new() { Id = 850, Code = 850, CityName = "باشت", ProvinceId = 22 },
                new() { Id = 851, Code = 851, CityName = "پاتاوه", ProvinceId = 22 },
                new() { Id = 852, Code = 852, CityName = "چرام", ProvinceId = 22 },
                new() { Id = 853, Code = 853, CityName = "چيتاب", ProvinceId = 22 },
                new() { Id = 854, Code = 854, CityName = "دوگنبدان", ProvinceId = 22 },
                new() { Id = 855, Code = 855, CityName = "دهدشت", ProvinceId = 22 },
                new() { Id = 856, Code = 856, CityName = "ديشموك", ProvinceId = 22 },
                new() { Id = 857, Code = 857, CityName = "سوق", ProvinceId = 22 },
                new() { Id = 858, Code = 858, CityName = "سي سخت", ProvinceId = 22 },
                new() { Id = 859, Code = 859, CityName = "قلعه رئيسي", ProvinceId = 22 },
                new() { Id = 860, Code = 860, CityName = "گراب سفلي", ProvinceId = 22 },
                new() { Id = 861, Code = 861, CityName = "لنده", ProvinceId = 22 },
                new() { Id = 862, Code = 862, CityName = "ليكك", ProvinceId = 22 },
                new() { Id = 863, Code = 863, CityName = "مادوان", ProvinceId = 22 },
                new() { Id = 864, Code = 864, CityName = "مارگون", ProvinceId = 22 },
                new() { Id = 865, Code = 865, CityName = "ياسوج", ProvinceId = 22 },
                new() { Id = 866, Code = 866, CityName = "انبارآلوم", ProvinceId = 23 },
                new() { Id = 867, Code = 867, CityName = "اينچه برون", ProvinceId = 23 },
                new() { Id = 868, Code = 868, CityName = "آزادشهر", ProvinceId = 23 },
                new() { Id = 869, Code = 869, CityName = "آق قلا", ProvinceId = 23 },
                new() { Id = 870, Code = 870, CityName = "بندرگز", ProvinceId = 23 },
                new() { Id = 871, Code = 871, CityName = "تركمن", ProvinceId = 23 },
                new() { Id = 872, Code = 872, CityName = "جلين", ProvinceId = 23 },
                new() { Id = 873, Code = 873, CityName = "خان ببين", ProvinceId = 23 },
                new() { Id = 874, Code = 874, CityName = "دلند", ProvinceId = 23 },
                new() { Id = 875, Code = 875, CityName = "راميان", ProvinceId = 23 },
                new() { Id = 876, Code = 876, CityName = "سرخنكلاته", ProvinceId = 23 },
                new() { Id = 877, Code = 877, CityName = "سيمين شهر", ProvinceId = 23 },
                new() { Id = 878, Code = 878, CityName = "علي آباد", ProvinceId = 23 },
                new() { Id = 879, Code = 879, CityName = "فاضل آباد", ProvinceId = 23 },
                new() { Id = 880, Code = 880, CityName = "كردكوي", ProvinceId = 23 },
                new() { Id = 881, Code = 881, CityName = "كلاله", ProvinceId = 23 },
                new() { Id = 882, Code = 882, CityName = "گاليكش", ProvinceId = 23 },
                new() { Id = 883, Code = 883, CityName = "گرگان", ProvinceId = 23 },
                new() { Id = 884, Code = 884, CityName = "گميش تپه", ProvinceId = 23 },
                new() { Id = 885, Code = 885, CityName = "گنبد كاووس", ProvinceId = 23 },
                new() { Id = 886, Code = 886, CityName = "مراوه تپه", ProvinceId = 23 },
                new() { Id = 887, Code = 887, CityName = "مينودشت", ProvinceId = 23 },
                new() { Id = 888, Code = 888, CityName = "نگين شهر", ProvinceId = 23 },
                new() { Id = 889, Code = 889, CityName = "نوده خاندوز", ProvinceId = 23 },
                new() { Id = 890, Code = 890, CityName = "نوكنده", ProvinceId = 23 },
                new() { Id = 891, Code = 891, CityName = "احمدسرگوراب", ProvinceId = 24 },
                new() { Id = 892, Code = 892, CityName = "اسالم", ProvinceId = 24 },
                new() { Id = 893, Code = 893, CityName = "اطاقور", ProvinceId = 24 },
                new() { Id = 894, Code = 894, CityName = "املش", ProvinceId = 24 },
                new() { Id = 895, Code = 895, CityName = "آستارا", ProvinceId = 24 },
                new() { Id = 896, Code = 896, CityName = "آستانه اشرفيه", ProvinceId = 24 },
                new() { Id = 897, Code = 897, CityName = "بازارجمعه", ProvinceId = 24 },
                new() { Id = 898, Code = 898, CityName = "بره سر", ProvinceId = 24 },
                new() { Id = 899, Code = 899, CityName = "بندرانزلي", ProvinceId = 24 },
                new() { Id = 900, Code = 900, CityName = "پره سر", ProvinceId = 24 },
                new() { Id = 901, Code = 901, CityName = "توتكابن", ProvinceId = 24 },
                new() { Id = 902, Code = 902, CityName = "جيرنده", ProvinceId = 24 },
                new() { Id = 903, Code = 903, CityName = "چابكسر", ProvinceId = 24 },
                new() { Id = 904, Code = 904, CityName = "چاف وچمخاله", ProvinceId = 24 },
                new() { Id = 905, Code = 905, CityName = "چوبر", ProvinceId = 24 },
                new() { Id = 906, Code = 906, CityName = "حويق", ProvinceId = 24 },
                new() { Id = 907, Code = 907, CityName = "خشكبيجار", ProvinceId = 24 },
                new() { Id = 908, Code = 908, CityName = "خمام", ProvinceId = 24 },
                new() { Id = 909, Code = 909, CityName = "ديلمان", ProvinceId = 24 },
                new() { Id = 910, Code = 910, CityName = "رانكوه", ProvinceId = 24 },
                new() { Id = 911, Code = 911, CityName = "رحيم آباد", ProvinceId = 24 },
                new() { Id = 912, Code = 912, CityName = "رستم آباد", ProvinceId = 24 },
                new() { Id = 913, Code = 913, CityName = "رشت", ProvinceId = 24 },
                new() { Id = 914, Code = 914, CityName = "رضوانشهر ", ProvinceId = 24 },
                new() { Id = 915, Code = 915, CityName = "رودبار ", ProvinceId = 24 },
                new() { Id = 916, Code = 916, CityName = "رودبنه", ProvinceId = 24 },
                new() { Id = 917, Code = 917, CityName = "رودسر", ProvinceId = 24 },
                new() { Id = 918, Code = 918, CityName = "سنگر", ProvinceId = 24 },
                new() { Id = 919, Code = 919, CityName = "سياهكل", ProvinceId = 24 },
                new() { Id = 920, Code = 920, CityName = "شفت", ProvinceId = 24 },
                new() { Id = 921, Code = 921, CityName = "شلمان", ProvinceId = 24 },
                new() { Id = 922, Code = 922, CityName = "صومعه سرا", ProvinceId = 24 },
                new() { Id = 923, Code = 923, CityName = "فومن", ProvinceId = 24 },
                new() { Id = 924, Code = 924, CityName = "كلاچاي", ProvinceId = 24 },
                new() { Id = 925, Code = 925, CityName = "كوچصفهان", ProvinceId = 24 },
                new() { Id = 926, Code = 926, CityName = "كومله", ProvinceId = 24 },
                new() { Id = 927, Code = 927, CityName = "كياشهر", ProvinceId = 24 },
                new() { Id = 928, Code = 928, CityName = "گوراب زرميخ", ProvinceId = 24 },
                new() { Id = 929, Code = 929, CityName = "لاهيجان", ProvinceId = 24 },
                new() { Id = 930, Code = 930, CityName = "لشت نشاء", ProvinceId = 24 },
                new() { Id = 931, Code = 931, CityName = "لنگرود", ProvinceId = 24 },
                new() { Id = 932, Code = 932, CityName = "لوشان", ProvinceId = 24 },
                new() { Id = 933, Code = 933, CityName = "لولمان", ProvinceId = 24 },
                new() { Id = 934, Code = 934, CityName = "لوندويل", ProvinceId = 24 },
                new() { Id = 935, Code = 935, CityName = "ليسار", ProvinceId = 24 },
                new() { Id = 936, Code = 936, CityName = "ماسال", ProvinceId = 24 },
                new() { Id = 937, Code = 937, CityName = "ماسوله", ProvinceId = 24 },
                new() { Id = 938, Code = 938, CityName = "مرجقل", ProvinceId = 24 },
                new() { Id = 939, Code = 939, CityName = "منجيل", ProvinceId = 24 },
                new() { Id = 940, Code = 940, CityName = "واجارگاه", ProvinceId = 24 },
                new() { Id = 941, Code = 941, CityName = "هشتپر", ProvinceId = 24 },
                new() { Id = 942, Code = 942, CityName = "ازنا", ProvinceId = 25 },
                new() { Id = 943, Code = 943, CityName = "اشترينان", ProvinceId = 25 },
                new() { Id = 944, Code = 944, CityName = "الشتر", ProvinceId = 25 },
                new() { Id = 945, Code = 945, CityName = "اليگودرز", ProvinceId = 25 },
                new() { Id = 946, Code = 946, CityName = "بروجرد", ProvinceId = 25 },
                new() { Id = 947, Code = 947, CityName = "پلدختر", ProvinceId = 25 },
                new() { Id = 948, Code = 948, CityName = "چالانچولان", ProvinceId = 25 },
                new() { Id = 949, Code = 949, CityName = "چغلوندي", ProvinceId = 25 },
                new() { Id = 950, Code = 950, CityName = "چقابل", ProvinceId = 25 },
                new() { Id = 951, Code = 951, CityName = "خرم آباد", ProvinceId = 25 },
                new() { Id = 952, Code = 952, CityName = "درب گنبد", ProvinceId = 25 },
                new() { Id = 953, Code = 953, CityName = "دورود", ProvinceId = 25 },
                new() { Id = 954, Code = 954, CityName = "زاغه", ProvinceId = 25 },
                new() { Id = 955, Code = 955, CityName = "سپيددشت", ProvinceId = 25 },
                new() { Id = 956, Code = 956, CityName = "سراب دوره", ProvinceId = 25 },
                new() { Id = 957, Code = 957, CityName = "شول آباد", ProvinceId = 25 },
                new() { Id = 958, Code = 958, CityName = "فيروز آباد", ProvinceId = 25 },
                new() { Id = 959, Code = 959, CityName = "كوناني", ProvinceId = 25 },
                new() { Id = 960, Code = 960, CityName = "كوهدشت", ProvinceId = 25 },
                new() { Id = 961, Code = 961, CityName = "گراب", ProvinceId = 25 },
                new() { Id = 962, Code = 962, CityName = "معمولان", ProvinceId = 25 },
                new() { Id = 963, Code = 963, CityName = "مؤمن آباد", ProvinceId = 25 },
                new() { Id = 964, Code = 964, CityName = "نور آباد", ProvinceId = 25 },
                new() { Id = 965, Code = 965, CityName = "ويسيان", ProvinceId = 25 },
                new() { Id = 966, Code = 966, CityName = "هفت چشمه", ProvinceId = 25 },
                new() { Id = 967, Code = 967, CityName = "اميركلا", ProvinceId = 26 },
                new() { Id = 968, Code = 968, CityName = "ايزدشهر", ProvinceId = 26 },
                new() { Id = 969, Code = 969, CityName = "آلاشت", ProvinceId = 26 },
                new() { Id = 970, Code = 970, CityName = "آمل", ProvinceId = 26 },
                new() { Id = 971, Code = 971, CityName = "بابل", ProvinceId = 26 },
                new() { Id = 972, Code = 972, CityName = "بابلسر", ProvinceId = 26 },
                new() { Id = 973, Code = 973, CityName = "بلده", ProvinceId = 26 },
                new() { Id = 974, Code = 974, CityName = "بهشهر", ProvinceId = 26 },
                new() { Id = 975, Code = 975, CityName = "بهنمير", ProvinceId = 26 },
                new() { Id = 976, Code = 976, CityName = "پل سفيد", ProvinceId = 26 },
                new() { Id = 977, Code = 977, CityName = "پول", ProvinceId = 26 },
                new() { Id = 978, Code = 978, CityName = "تنكابن", ProvinceId = 26 },
                new() { Id = 979, Code = 979, CityName = "جويبار", ProvinceId = 26 },
                new() { Id = 980, Code = 980, CityName = "چالوس", ProvinceId = 26 },
                new() { Id = 981, Code = 981, CityName = "چمستان", ProvinceId = 26 },
                new() { Id = 982, Code = 982, CityName = "خرم آباد ", ProvinceId = 26 },
                new() { Id = 983, Code = 983, CityName = "خليل شهر", ProvinceId = 26 },
                new() { Id = 984, Code = 984, CityName = "خوش رودپي", ProvinceId = 26 },
                new() { Id = 985, Code = 985, CityName = "دابودشت", ProvinceId = 26 },
                new() { Id = 986, Code = 986, CityName = "رامسر", ProvinceId = 26 },
                new() { Id = 987, Code = 987, CityName = "رستمكلا", ProvinceId = 26 },
                new() { Id = 988, Code = 988, CityName = "رويان", ProvinceId = 26 },
                new() { Id = 989, Code = 989, CityName = "رينه", ProvinceId = 26 },
                new() { Id = 990, Code = 990, CityName = "زرگر محله", ProvinceId = 26 },
                new() { Id = 991, Code = 991, CityName = "زيرآب", ProvinceId = 26 },
                new() { Id = 992, Code = 992, CityName = "ساري", ProvinceId = 26 },
                new() { Id = 993, Code = 993, CityName = "سرخرود", ProvinceId = 26 },
                new() { Id = 994, Code = 994, CityName = "سلمان شهر", ProvinceId = 26 },
                new() { Id = 995, Code = 995, CityName = "سورك", ProvinceId = 26 },
                new() { Id = 996, Code = 996, CityName = "شيرگاه", ProvinceId = 26 },
                new() { Id = 997, Code = 997, CityName = "شيرود", ProvinceId = 26 },
                new() { Id = 998, Code = 998, CityName = "عباس آباد", ProvinceId = 26 },
                new() { Id = 999, Code = 999, CityName = "فريدونكنار", ProvinceId = 26 },
                new() { Id = 1000, Code = 1000, CityName = "فريم", ProvinceId = 26 },
                new() { Id = 1001, Code = 1001, CityName = "قائم شهر", ProvinceId = 26 },
                new() { Id = 1002, Code = 1002, CityName = "كتالم وسادات شهر", ProvinceId = 26 },
                new() { Id = 1003, Code = 1003, CityName = "كلارآباد", ProvinceId = 26 },
                new() { Id = 1004, Code = 1004, CityName = "كلاردشت", ProvinceId = 26 },
                new() { Id = 1005, Code = 1005, CityName = "كله بست", ProvinceId = 26 },
                new() { Id = 1006, Code = 1006, CityName = "كوهي خيل", ProvinceId = 26 },
                new() { Id = 1007, Code = 1007, CityName = "كياسر", ProvinceId = 26 },
                new() { Id = 1008, Code = 1008, CityName = "كياكلا", ProvinceId = 26 },
                new() { Id = 1009, Code = 1009, CityName = "گتاب", ProvinceId = 26 },
                new() { Id = 1010, Code = 1010, CityName = "گزنك", ProvinceId = 26 },
                new() { Id = 1011, Code = 1011, CityName = "گلوگاه", ProvinceId = 26 },
                new() { Id = 1012, Code = 1012, CityName = "محمود آباد", ProvinceId = 26 },
                new() { Id = 1013, Code = 1013, CityName = "مرزن آباد", ProvinceId = 26 },
                new() { Id = 1014, Code = 1014, CityName = "مرزيكلا", ProvinceId = 26 },
                new() { Id = 1015, Code = 1015, CityName = "نشتارود", ProvinceId = 26 },
                new() { Id = 1016, Code = 1016, CityName = "نكا", ProvinceId = 26 },
                new() { Id = 1017, Code = 1017, CityName = "نور", ProvinceId = 26 },
                new() { Id = 1018, Code = 1018, CityName = "نوشهر", ProvinceId = 26 },
                new() { Id = 1019, Code = 1019, CityName = "اراك", ProvinceId = 27 },
                new() { Id = 1020, Code = 1020, CityName = "آستانه", ProvinceId = 27 },
                new() { Id = 1021, Code = 1021, CityName = "آشتيان", ProvinceId = 27 },
                new() { Id = 1022, Code = 1022, CityName = "پرندك", ProvinceId = 27 },
                new() { Id = 1023, Code = 1023, CityName = "تفرش", ProvinceId = 27 },
                new() { Id = 1024, Code = 1024, CityName = "توره", ProvinceId = 27 },
                new() { Id = 1025, Code = 1025, CityName = "جاورسيان", ProvinceId = 27 },
                new() { Id = 1026, Code = 1026, CityName = "خشكرود", ProvinceId = 27 },
                new() { Id = 1027, Code = 1027, CityName = "خمين", ProvinceId = 27 },
                new() { Id = 1028, Code = 1028, CityName = "خنداب", ProvinceId = 27 },
                new() { Id = 1029, Code = 1029, CityName = "داودآباد", ProvinceId = 27 },
                new() { Id = 1030, Code = 1030, CityName = "دليجان", ProvinceId = 27 },
                new() { Id = 1031, Code = 1031, CityName = "رازقان", ProvinceId = 27 },
                new() { Id = 1032, Code = 1032, CityName = "زاويه", ProvinceId = 27 },
                new() { Id = 1033, Code = 1033, CityName = "ساروق", ProvinceId = 27 },
                new() { Id = 1034, Code = 1034, CityName = "ساوه", ProvinceId = 27 },
                new() { Id = 1035, Code = 1035, CityName = "سنجان", ProvinceId = 27 },
                new() { Id = 1036, Code = 1036, CityName = "شازند", ProvinceId = 27 },
                new() { Id = 1037, Code = 1037, CityName = "شهرجديدمهاجران", ProvinceId = 27 },
                new() { Id = 1038, Code = 1038, CityName = "غرق آباد", ProvinceId = 27 },
                new() { Id = 1039, Code = 1039, CityName = "فرمهين", ProvinceId = 27 },
                new() { Id = 1040, Code = 1040, CityName = "قورچي باشي", ProvinceId = 27 },
                new() { Id = 1041, Code = 1041, CityName = "كرهرود", ProvinceId = 27 },
                new() { Id = 1042, Code = 1042, CityName = "كميجان", ProvinceId = 27 },
                new() { Id = 1043, Code = 1043, CityName = "مأمونيه", ProvinceId = 27 },
                new() { Id = 1044, Code = 1044, CityName = "محلات", ProvinceId = 27 },
                new() { Id = 1045, Code = 1045, CityName = "ميلاجرد", ProvinceId = 27 },
                new() { Id = 1046, Code = 1046, CityName = "نراق", ProvinceId = 27 },
                new() { Id = 1047, Code = 1047, CityName = "نوبران", ProvinceId = 27 },
                new() { Id = 1048, Code = 1048, CityName = "نيمور", ProvinceId = 27 },
                new() { Id = 1049, Code = 1049, CityName = "هندودر", ProvinceId = 27 },
                new() { Id = 1050, Code = 1050, CityName = "ابوموسي", ProvinceId = 28 },
                new() { Id = 1051, Code = 1051, CityName = "بستك", ProvinceId = 28 },
                new() { Id = 1052, Code = 1052, CityName = "بندرجاسك", ProvinceId = 28 },
                new() { Id = 1053, Code = 1053, CityName = "بندرچارك", ProvinceId = 28 },
                new() { Id = 1054, Code = 1054, CityName = "بندرعباس", ProvinceId = 28 },
                new() { Id = 1055, Code = 1055, CityName = "بندرلنگه", ProvinceId = 28 },
                new() { Id = 1056, Code = 1056, CityName = "بيكاه", ProvinceId = 28 },
                new() { Id = 1057, Code = 1057, CityName = "پارسيان", ProvinceId = 28 },
                new() { Id = 1058, Code = 1058, CityName = "تخت", ProvinceId = 28 },
                new() { Id = 1059, Code = 1059, CityName = "جناح", ProvinceId = 28 },
                new() { Id = 1060, Code = 1060, CityName = "حاجي آباد  ", ProvinceId = 28 },
                new() { Id = 1061, Code = 1061, CityName = "خمير", ProvinceId = 28 },
                new() { Id = 1062, Code = 1062, CityName = "درگهان", ProvinceId = 28 },
                new() { Id = 1063, Code = 1063, CityName = "دهبارز", ProvinceId = 28 },
                new() { Id = 1064, Code = 1064, CityName = "رويدر", ProvinceId = 28 },
                new() { Id = 1065, Code = 1065, CityName = "زيارتعلي", ProvinceId = 28 },
                new() { Id = 1066, Code = 1066, CityName = "سردشت بشاگرد", ProvinceId = 28 },
                new() { Id = 1067, Code = 1067, CityName = "سرگز", ProvinceId = 28 },
                new() { Id = 1068, Code = 1068, CityName = "سندرك", ProvinceId = 28 },
                new() { Id = 1069, Code = 1069, CityName = "سوزا", ProvinceId = 28 },
                new() { Id = 1070, Code = 1070, CityName = "سيريك", ProvinceId = 28 },
                new() { Id = 1071, Code = 1071, CityName = "فارغان", ProvinceId = 28 },
                new() { Id = 1072, Code = 1072, CityName = "فين", ProvinceId = 28 },
                new() { Id = 1073, Code = 1073, CityName = "قشم", ProvinceId = 28 },
                new() { Id = 1074, Code = 1074, CityName = "قلعه قاضي", ProvinceId = 28 },
                new() { Id = 1075, Code = 1075, CityName = "كنگ", ProvinceId = 28 },
                new() { Id = 1076, Code = 1076, CityName = "كوشكنار", ProvinceId = 28 },
                new() { Id = 1077, Code = 1077, CityName = "كيش", ProvinceId = 28 },
                new() { Id = 1078, Code = 1078, CityName = "گوهران", ProvinceId = 28 },
                new() { Id = 1079, Code = 1079, CityName = "ميناب", ProvinceId = 28 },
                new() { Id = 1080, Code = 1080, CityName = "هرمز", ProvinceId = 28 },
                new() { Id = 1081, Code = 1081, CityName = "هشتبندي", ProvinceId = 28 },
                new() { Id = 1082, Code = 1082, CityName = "ازندريان", ProvinceId = 29 },
                new() { Id = 1083, Code = 1083, CityName = "اسدآباد", ProvinceId = 29 },
                new() { Id = 1084, Code = 1084, CityName = "برزول", ProvinceId = 29 },
                new() { Id = 1085, Code = 1085, CityName = "بهار", ProvinceId = 29 },
                new() { Id = 1086, Code = 1086, CityName = "تويسركان", ProvinceId = 29 },
                new() { Id = 1087, Code = 1087, CityName = "جورقان", ProvinceId = 29 },
                new() { Id = 1088, Code = 1088, CityName = "جوكار", ProvinceId = 29 },
                new() { Id = 1089, Code = 1089, CityName = "دمق", ProvinceId = 29 },
                new() { Id = 1090, Code = 1090, CityName = "رزن", ProvinceId = 29 },
                new() { Id = 1091, Code = 1091, CityName = "زنگنه", ProvinceId = 29 },
                new() { Id = 1092, Code = 1092, CityName = "سامن", ProvinceId = 29 },
                new() { Id = 1093, Code = 1093, CityName = "سركان", ProvinceId = 29 },
                new() { Id = 1094, Code = 1094, CityName = "شيرين سو", ProvinceId = 29 },
                new() { Id = 1095, Code = 1095, CityName = "صالح آباد   ", ProvinceId = 29 },
                new() { Id = 1096, Code = 1096, CityName = "فامنين", ProvinceId = 29 },
                new() { Id = 1097, Code = 1097, CityName = "فرسفج", ProvinceId = 29 },
                new() { Id = 1098, Code = 1098, CityName = "فيروزان", ProvinceId = 29 },
                new() { Id = 1099, Code = 1099, CityName = "قروه در جزين", ProvinceId = 29 },
                new() { Id = 1100, Code = 1100, CityName = "قهاوند", ProvinceId = 29 },
                new() { Id = 1101, Code = 1101, CityName = "كبودرآهنگ", ProvinceId = 29 },
                new() { Id = 1102, Code = 1102, CityName = "گل تپه", ProvinceId = 29 },
                new() { Id = 1103, Code = 1103, CityName = "گيان", ProvinceId = 29 },
                new() { Id = 1104, Code = 1104, CityName = "لالجين", ProvinceId = 29 },
                new() { Id = 1105, Code = 1105, CityName = "مريانج", ProvinceId = 29 },
                new() { Id = 1106, Code = 1106, CityName = "ملاير", ProvinceId = 29 },
                new() { Id = 1107, Code = 1107, CityName = "نهاوند", ProvinceId = 29 },
                new() { Id = 1108, Code = 1108, CityName = "همدان", ProvinceId = 29 },
                new() { Id = 1109, Code = 1109, CityName = "ابركوه", ProvinceId = 30 },
                new() { Id = 1110, Code = 1110, CityName = "احمدآباد", ProvinceId = 30 },
                new() { Id = 1111, Code = 1111, CityName = "اردكان ", ProvinceId = 30 },
                new() { Id = 1112, Code = 1112, CityName = "اشكذر", ProvinceId = 30 },
                new() { Id = 1113, Code = 1113, CityName = "بافق", ProvinceId = 30 },
                new() { Id = 1114, Code = 1114, CityName = "بفروئيه", ProvinceId = 30 },
                new() { Id = 1115, Code = 1115, CityName = "بهاباد", ProvinceId = 30 },
                new() { Id = 1116, Code = 1116, CityName = "تفت", ProvinceId = 30 },
                new() { Id = 1117, Code = 1117, CityName = "حميديا", ProvinceId = 30 },
                new() { Id = 1118, Code = 1118, CityName = "خضرآباد", ProvinceId = 30 },
                new() { Id = 1119, Code = 1119, CityName = "ديهوك", ProvinceId = 30 },
                new() { Id = 1120, Code = 1120, CityName = "زارچ", ProvinceId = 30 },
                new() { Id = 1121, Code = 1121, CityName = "شاهديه", ProvinceId = 30 },
                new() { Id = 1122, Code = 1122, CityName = "طبس", ProvinceId = 30 },
                new() { Id = 1123, Code = 1123, CityName = "عشق آباد ", ProvinceId = 30 },
                new() { Id = 1124, Code = 1124, CityName = "عقدا", ProvinceId = 30 },
                new() { Id = 1125, Code = 1125, CityName = "مروست", ProvinceId = 30 },
                new() { Id = 1126, Code = 1126, CityName = "مهردشت", ProvinceId = 30 },
                new() { Id = 1127, Code = 1127, CityName = "مهريز", ProvinceId = 30 },
                new() { Id = 1128, Code = 1128, CityName = "ميبد", ProvinceId = 30 },
                new() { Id = 1129, Code = 1129, CityName = "ندوشن", ProvinceId = 30 },
                new() { Id = 1130, Code = 1130, CityName = "نير ", ProvinceId = 30 },
                new() { Id = 1131, Code = 1131, CityName = "هرات", ProvinceId = 30 },
                new() { Id = 1132, Code = 1132, CityName = "يزد", ProvinceId = 30 });


        }
    }
}
